Repository undertow-io/undertow, pull requests merged in 2019-10, with the labels that each got.

#817 UNDERTOW-1576: BASIC auth password is output as plain text at DEBUG level logging in BasicAuthenticationMechanism
  core/src/main/java/io/undertow/security/impl/BasicAuthenticationMechanism.java
Labels: bug, next release, waiting CI check

#819 UNDERTOW-1606 Output undertow version logging at INFO level on Undert…
  core/src/main/java/io/undertow/Undertow.java
Labels: enhancement, next release

#790 Add unit tests for io.undertow.util.ByteRange
  core/src/test/java/io/undertow/util/ByteRangeTestCase.java
Labels: enhancement, next release

#815 UNDERTOW-1599 ServletRequestLineAttribute does not output the origina…
  servlet/src/main/java/io/undertow/servlet/attribute/ServletRequestLineAttribute.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
Labels: bug, next release

#820 [UNDERTOW-1603][UNDERTOW-1604][UNDERTOW-1605]Suspend reads if the num…
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: bug, next release, waiting CI check

#808 Fixing rewrite handler so that it properly routes to destination servlet
  servlet/src/main/java/io/undertow/servlet/compat/rewrite/RewriteHandler.java
  servlet/src/test/java/io/undertow/servlet/test/compat/rewrite/RewriteTestCase.java
Labels: bug, next release

#821 [UNDERTOW-1602] Don't immediatly attempt to resume if parsing was uns…
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: bug, next release, waiting CI check
