Repository undertow-io/undertow, pull requests merged in 2019-08, with the labels that each got.

#796 [UNDERTOW-1580] Improve EJB over HTTPS logging
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: enhancement, next release

#798 UNDERTOW-1582 Fix NPE while setting up temporary directory
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
  servlet/src/main/java/io/undertow/servlet/api/SecurityActions.java
  servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java
Labels: bug, next release, waiting PR update

#805 [UNDERTOW-1554] Improve handling and leniency of bad POST parameters
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java
  core/src/main/java/io/undertow/util/UrlDecodeException.java
  core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Labels: next release

#797 [UNDERTOW-1573] Servlet request attributes are cleared before access log exchange completion listener runs
  servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/test/java/io/undertow/servlet/test/proprietry/ExchangeCompletionTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/proprietry/IgnoresRequestAndSetsAttributeAsyncServlet.java
  servlet/src/test/java/io/undertow/servlet/test/proprietry/IgnoresRequestAndSetsAttributeServlet.java
Labels: next release

#799 UNDERTOW-1581: Fix RoutingHandler allMethodsMatcher validation
  core/src/main/java/io/undertow/server/RoutingHandler.java
  core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java
Labels: bug, next release

#806 UNDERTOW-1588: Fix off-by-one error in header resolution
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
Labels: next release
