Repository undertow-io/undertow, pull requests merged in 2020-03, with the labels that each got.

#859 UNDERTOW-1667 Change AjpRequestParser to ignore unknown request attri…
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpOpenListener.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/ajp/SecurityActions.java
Labels: bug, next release

#848 [UNDERTOW-1646] Inconsistent parameter count on file upload
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: bug, next release

#841 UNDERTOW-1638: Fix AbstractFramedStreamSinkChannel resource release race
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug, next release

#842 UNDERTOW-1639: AbstractFramedStreamSourceChannel notifies on close
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Labels: bug, next release

#863 [UNDERTOW-1611] Update counts and notify callback when getting RuntimeException at ProxyPoolConnection.openConnection
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyConnectionPool.java
Labels: enhancement, next release

#844 [UNDERTOW-1670] DefaultServer test utility waits for the worker to shut down
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: bug, next release

#846 UNDERTOW-1645: AbstractFramedStreamSourceChannel.lastFrame invokes close
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Labels: bug, next release

#843 UNDERTOW-1641: Reset interruption on InterruptedException
  core/src/main/java/io/undertow/Undertow.java
  core/src/main/java/io/undertow/conduits/RateLimitingStreamSinkConduit.java
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyConnectionPool.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: enhancement, next release

#856 [UNDERTOW-1492] Respect rfc7230 section-3.3.2
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
Labels: bug, next release

#865 [UNDERTOW-1663] Handle javax.net.ssl.SSLEngineResult.Status#BUFFER_OV…
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/test/java/io/undertow/server/handlers/session/SSLSessionWithExpandedBufferTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataWithExpandedBufferTestCase.java
Labels: bug, next release

#869 [UNDERTOW-1663] Make the expanded buffer pool volatile
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug, next release, waiting CI check

#867 UNDERTOW-1661 Make sure isComplete() is true if listeners are invoked
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: bug, next release, waiting CI check

#868 [UNDERTOW-1671] Fix URLUtils path param parsing by using ';' as the c…
  core/src/main/java/io/undertow/util/URLUtils.java
Labels: bug, next release

#871 [UNDERTOW-1464][UNDERTOW-1671] Fix path param parsing
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/session/ServletSessionTestCase.java
Labels: bug, failed CI, next release, waiting PR update

#816 UNDERTOW-1600 Enhance SameSite cookie support
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/handlers/Cookie.java
  core/src/main/java/io/undertow/server/handlers/CookieImpl.java
  core/src/main/java/io/undertow/server/handlers/CookieSameSiteMode.java
  core/src/main/java/io/undertow/server/handlers/SameSiteCookieHandler.java
  core/src/main/java/io/undertow/util/Cookies.java
  core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
  core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
  core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
  core/src/test/java/io/undertow/util/CookiesTestCase.java
  core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletCookieAdaptor.java
Labels: enhancement, new feature, next release

#833 [UNDERTOW-1672] Unable to find the resource: /META-INF/BenchmarkList
  benchmarks/pom.xml
Labels: bug, next release

#872 UNDERTOW-1677 cross context request issue with shared session managers
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletSharedSessionTestCase.java
Labels: bug, next release
