Repository undertow-io/undertow, pull requests merged in 2020-02, with the labels that each got.

#836 UNDERTOW-1629 reduce severity of logging on ssl client handshake fail
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: enhancement, next release

#832 UNDERTOW-1464 Proper handling of matrix parameters
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/ParseState.java
  core/src/main/java/io/undertow/server/session/PathParameterSessionConfig.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Labels: bug, under verification, waiting CI check

#840 [UNDERTOW-1637] Redirect Form auth on root context without trailing s…
  core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
  servlet/src/test/java/io/undertow/servlet/test/security/form/FormAuthenticationRootContextRedirectTestCase.java
Labels: bug, next release, waiting CI check

#847 UNDERTOW-1643: Prevent deadlock in AbstractFramedStreamSinkChannel
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Labels: bug, next release
