Repository undertow-io/undertow, pull requests merged in 2020-01, with the labels that each got.

#829 [UNDERTOW-1624] At AbstractFramedStreamSinkChannel.resumeWritesIntern…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug, next release

#789 [UNDERTOW-1570] Websocket messages lost when ClientEndpointConfig provided
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/ServerWebSocketContainer.java
Labels: bug, next release, waiting CI check

#827 [UNDERTOW-1618][UNDERTOW-1619][UNDERTOW-1620] Fix issues with abstract framed channels
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Labels: bug, next release, waiting CI check

#828 [UNDERTOW-1623] Prevent the deadlock by invoking AbstractFramedChanne…
  core/src/main/java/io/undertow/protocols/ajp/AjpClientChannel.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
  core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
Labels: bug, next release, waiting CI check

#831 UNDERTOW-1627 gzip encoding is not enabled by RequestEncodingHandler$…
  core/src/main/java/io/undertow/server/handlers/encoding/RequestEncodingHandler.java
  core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
Labels: enhancement, next release

#835 [UNDERTOW-1630] RewriteHandler rewite url env lost
  servlet/src/main/java/io/undertow/servlet/compat/rewrite/RewriteHandler.java
Labels: bug, next release

#834 [UNDERTOW-1634] replace "/" to File.separator
  examples/src/main/java/io/undertow/examples/Runner.java
Labels: bug

#839 [UNDERTOW-1635] Mark the javadoc plugin source code compatible with 1.8
  pom.xml
Labels: bug, next release, waiting CI check
