Repository undertow-io/undertow, pull requests merged in 2020-05, with the labels that each got.

#882 [UNDERTOW-1703] Checking isSymbolicLink should be in doPrivileged block
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/SecurityActions.java
Labels: bug, next release

#883 [UNDERTOW-1703] Checking isSymbolicLink should be in doPrivileged block
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/SecurityActions.java
Labels: bug, waiting PR update

#884 [Undertow 1702] SameSiteCookieHandler can throw NPE if request doesn't contain user-agent header
  core/src/main/java/io/undertow/server/handlers/SameSiteCookieHandler.java
  core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
  core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
  core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
Labels: enhancement, next release

#886 UNDERTOW-1419 At InMemorySessionMemoryManager bump timeout only when …
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug, next release

#887 [UNDERTOW-1710] Update the Netty version to 4.1.50.Final
  pom.xml
Labels: enhancement, next release

#888 [UNDERTOW-1708] Invalid HTTP Request with large chunk file
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/conduits/ChunkReader.java
Labels: bug, next release

#880 UNDERTOW-1197 Make sure async dispatch happens with current request/re…
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: bug, next release

#889 [UNDERTOW-1657] Memory exhaustion issue in HttpReadListener and related fixes
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/handlers/HttpContinueReadHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
  core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/main/java/io/undertow/server/protocol/http/HttpServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
  core/src/test/java/io/undertow/server/handlers/HttpContinueConduitWrappingHandlerBufferLeakTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueServletTestCase.java
Labels: bug, next release

#890 [UNDERTOW-1706] Fix issue with wildfly-common dependency and maven en…
  pom.xml
Labels: bug, next release

#894 UNDERTOW-1716 Allow colon in the request cookie value regardless of t…
  core/src/main/java/io/undertow/util/Cookies.java
  core/src/test/java/io/undertow/util/CookiesTestCase.java
Labels: enhancement, next release
