Repository undertow-io/undertow, pull requests merged in 2020-09, with the labels that each got.

#881 [UNDERTOW-1662] Add support for External HTTP authentication mechanis…
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
Labels: enhancement, waiting PR update

#837 UNDERTOW-1622: Implement blocking IO timeouts
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java
  core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java
  core/src/test/java/io/undertow/server/handlers/BlockingReadTimeoutHandlerTestCase.java
  core/src/test/java/io/undertow/server/handlers/BlockingWriteTimeoutHandlerTestCase.java
Labels: new feature, next release

#858 UNDERTOW-1664: Prevent errors when http/2 channels are terminated
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: bug, next release

#905 [UNDERTOW-1732] Verify if we have a SecurityContext before making use of it.
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: enhancement, next release

#927 UNDERTOW-1772 Delay init of application listeners after servlet conta…
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
Labels: enhancement, next release

#850 [UNDERTOW-1779] Mark several fields of Http2Channel as final
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
Labels: enhancement, next release

#903 [UNDERTOW-1724] Remove the @RunWith from SameSiteCookieHandler, so th…
  core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
Labels: enhancement, next release, under verification

#918 UNDERTOW-1764 Websocket client was calling .handshake twice
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: bug, next release

#919 UNDERTOW-1766 Fix SSL Renegotiation on JDK14
  core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
Labels: bug, next release

#920 UNDERTOW-1765 Fix SPNEGO tests on Windows JDK11
  core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java
Labels: bug, next release

#922 UNDERTOW-1763 DefaultAccessLogReceiver has a concurrency issue that t…
  core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
Labels: bug, next release

#925 UNDERTOW-1770 HttpString uses obsolete String Constructor
  core/src/main/java/io/undertow/util/HttpString.java
Labels: enhancement, next release

#949 UNDERTOW-1773 to avoid potential leak, make sure the iteration continue in case of exception.
  servlet/src/main/java/io/undertow/servlet/core/ApplicationListeners.java
Labels: bug, next release

#924 [UNDERTOW-1782][WFLY-13748]: fix for Contains non-LDH ASCII during ejb remote call in …
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Labels: bug, next release

#948 UNDERTOW-1747 - Provide a mechanism for a predicate in return a servlet error page
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/server/handlers/SetErrorHandler.java
  core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
  servlet/src/main/java/io/undertow/servlet/handlers/SendErrorPageHandler.java
Labels: new feature, next release

#951 [UNDERTOW-1780][JBEAP-18537] Validating request headers in HTTP2 frames
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: bug, next release, waiting CI check

#874 [UNDERTOW-1783] Add support for part specific charsets. Charset is captured during pa…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: enhancement, next release

#954 UNDERTOW-1773 to avoid leak, make sure the iteration continue in case…
  servlet/src/main/java/io/undertow/servlet/core/ApplicationListeners.java
Labels: bug, maintenance branch, waiting CI check

#953 UNDERTOW-1773 to avoid leak, make sure the iteration continue in case…
  servlet/src/main/java/io/undertow/servlet/core/ApplicationListeners.java
Labels: bug, maintenance branch, waiting CI check

#957 [UNDERTOW-1788] prefer FORWARD_REQUEST_URI over ERROR_REQUEST_URI
  servlet/src/main/java/io/undertow/servlet/attribute/ServletRequestURLAttribute.java
Labels: bug, maintenance branch

#958 [UNDERTOW-1788] prefer FORWARD_REQUEST_URI over ERROR_REQUEST_URI
  servlet/src/main/java/io/undertow/servlet/attribute/ServletRequestURLAttribute.java
Labels: bug, maintenance branch

#960 [UNDERTOW-1782][WFLY-13748]: fix for Contains non-LDH ASCII during ejb remote call in ipv6 network
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Labels: bug, maintenance branch

#959 [UNDERTOW-1782][WFLY-13748]: fix for Contains non-LDH ASCII during ejb remote call in ipv6 network
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Labels: bug, maintenance branch

#961 UNDERTOW-1763 DefaultAccessLogReceiver has a concurrency issue that throws "IOException: Stream closed" or NullPointerException
  core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
Labels: bug, maintenance branch

#962 UNDERTOW-1763 DefaultAccessLogReceiver has a concurrency issue that throws "IOException: Stream closed" or NullPointerException
  core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
Labels: bug, maintenance branch

#964 UNDERTOW-1766 Fix SSL Renegotiation on JDK14
  core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
Labels: bug, maintenance branch

#963 UNDERTOW-1766 Fix SSL Renegotiation on JDK14
  core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
Labels: bug, maintenance branch

#965 UNDERTOW-1767 Remove hack from TestResourceLoader
  servlet/src/test/java/io/undertow/servlet/test/util/TestResourceLoader.java
  servlet/src/test/resources/logging.properties
Labels: maintenance branch

#966 UNDERTOW-1767 Remove hack from TestResourceLoader
  servlet/src/test/java/io/undertow/servlet/test/util/TestResourceLoader.java
  servlet/src/test/resources/logging.properties
Labels: maintenance branch

#967 UNDERTOW-1765 Fix SPNEGO tests on Windows JDK11
  core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java
Labels: bug, maintenance branch

#968 UNDERTOW-1765 Fix SPNEGO tests on Windows JDK11
  core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java
Labels: bug, maintenance branch

#970 UNDERTOW-1764 Websocket client was calling .handshake twice
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: bug, maintenance branch

#969 UNDERTOW-1764 Websocket client was calling .handshake twice
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: bug, maintenance branch

#971 [UNDERTOW-1724] Remove the @RunWith from SameSiteCookieHandlerTestCase
  core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
Labels: bug, maintenance branch
