Repository undertow-io/undertow, pull requests merged in 2020-08, with the labels that each got.

#928 [UNDERTOW-1708] Invalid HTTP Request with large chunk file
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/conduits/ChunkReader.java
Labels: bug, maintenance branch

#929 [UNDERTOW-1657] Memory exhaustion issue in HttpReadListener and related fixes
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/handlers/HttpContinueReadHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
  core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/main/java/io/undertow/server/protocol/http/HttpServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
  core/src/test/java/io/undertow/server/handlers/HttpContinueConduitWrappingHandlerBufferLeakTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueServletTestCase.java
Labels: bug, maintenance branch

#930 [UNDERTOW-1464][UNDERTOW-1671] Proper parsing of matrix parameters
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/session/ServletSessionTestCase.java
Labels: bug, maintenance branch

#931 UNDERTOW-1677 cross context request issue with shared session managers
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletSharedSessionTestCase.java
Labels: bug, maintenance branch

#933 [JBEAP-18580][UNDERTOW-1774] Treat whitespace as illegal in header fi…
  parser-generator/src/main/java/io/undertow/annotationprocessor/AbstractParserGenerator.java
Labels: bug, maintenance branch

#934 UNDERTOW-1683 Don't throw an exception if isReady is called before re…
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/EagerAsyncInputStreamServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
Labels: bug, maintenance branch

#935 UNDERTOW-1197 Make sure async dispatch happens with current requst/re…
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: bug, maintenance branch

#936 UNDERTOW-1419 At InMemorySessionMemoryManager bump timeout only when …
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug, maintenance branch

#932 [JBEAP-18580][UNDERTOW-1774] Treat whitespace as illegal in header fi…
  parser-generator/src/main/java/io/undertow/annotationprocessor/AbstractParserGenerator.java
Labels: bug, next release

#937 UNDERTOW-1716 Allow colon in the request cookie value regardless of t…
  core/src/main/java/io/undertow/util/Cookies.java
  core/src/test/java/io/undertow/util/CookiesTestCase.java
Labels: bug, maintenance branch

#938 [UNDERTOW-1726] Disable the JDK9AlpnProvider from being used by defau…
  core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
Labels: bug, maintenance branch

#939 UNDERTOW-1717 Return 416 Range Not Satisfiable when first-byte-pos of…
  core/src/main/java/io/undertow/util/ByteRange.java
  core/src/test/java/io/undertow/server/handlers/RangeRequestTestCase.java
  core/src/test/java/io/undertow/util/ByteRangeTestCase.java
Labels: bug, maintenance branch

#940 UNDERTOW-1720 fix potential race in senders
  core/src/main/java/io/undertow/io/AsyncSenderImpl.java
  core/src/main/java/io/undertow/io/BlockingSenderImpl.java
  servlet/src/main/java/io/undertow/servlet/core/BlockingWriterSenderImpl.java
Labels: bug, maintenance branch

#941 UNDERTOW-1713 Don't start async IO too early
  servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: bug, maintenance branch

#942 [UNDERTOW-1722] Resolve memory leak involving request attributes
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, maintenance branch

#943 UNDERTOW-1667 follow-up - Avoid loop iteration for checking known att…
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
Labels: bug, maintenance branch

#917 [UNDERTOW-1762] Error page for custom exception-type is not is not displayed in jsp development mode
  servlet/src/main/java/io/undertow/servlet/core/ErrorPages.java
Labels: bug, next release

#944 [UNDERTOW-1762] Error page for custom exception-type is not is not displayed in jsp development mode
  servlet/src/main/java/io/undertow/servlet/core/ErrorPages.java
Labels: bug, maintenance branch

#913 [UNDERTOW-1755] - remove doubled definitions of some variables
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
Labels: enhancement, next release, waiting CI check

#914 [UNDERTOW-1755] - remove doubled definitions of some variables
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
Labels: maintenance branch

#946 UNDERTOW-1701: Fix race condition in GracefulShutdownHandler
  core/src/main/java/io/undertow/server/handlers/GracefulShutdownHandler.java
Labels: bug, maintenance branch

#947 Adding test to InMemorySessionTestCase for UNDERTOW-1419
  core/src/test/java/io/undertow/server/handlers/session/InMemorySessionTestCase.java
Labels: enhancement, maintenance branch

#945 Revert "UNDERTOW-1747 - Provide a mechanism for a predicate in return a servlet error page"
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/server/handlers/SetErrorHandler.java
  core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
  servlet/src/main/java/io/undertow/servlet/handlers/SendErrorPageHandler.java
Labels: maintenance branch
