Repository undertow-io/undertow, pull requests merged in 2020-12, with the labels that each got.

#1002 [UNDERTOW-1817] Enhance error page handling to be spec compliant
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/test/java/io/undertow/servlet/test/errorpage/ErrorPageTestCase.java
Labels: bug, next release

#996 UNDERTOW-1812: Fail fast when renegotiation is requested using TLSv1.3
  core/src/main/java/io/undertow/server/ConnectionSSLSessionInfo.java
Labels: enhancement, next release

#991 [UNDERTOW-1820] Fix flaky test in SaveOriginalPostRequestTestCase
  servlet/src/test/java/io/undertow/servlet/test/security/form/SaveOriginalPostRequestTestCase.java
Labels: enhancement, next release

#982 [JBEAP-20391][JBEAP-20392][UNDERTOW-1796][UNDERTOW-1800] Default the io.undertow.protocols.alpn.jdk8 to true and change the order of preferred providers
  core/src/main/java/io/undertow/protocols/alpn/JDK8HackAlpnProvider.java
  core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
Labels: maintenance branch

#980 [UNDERTOW-1802] Improve FormEncodedDataDefinition to handle chars in configured encoding
  core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Labels: bug, next release

#979 [UNDERTOW-1802] Improve FormEncodedDataDefinition to handle chars in configured encoding
  core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Labels: maintenance branch

#978 [UNDERTOW-1802] Improve FormEncodedDataDefinition to handle chars in configured encoding
  core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Labels: maintenance branch

#976 [UNDERTOW-1796] [UNDERTOW-1800] Default the io.undertow.protocols.alpn.jdk8 to true and change the order of preferred providers
  core/src/main/java/io/undertow/protocols/alpn/JDK8HackAlpnProvider.java
  core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
Labels: enhancement, maintenance branch

#988 UNDERTOW-1791: Migrate from getPeerCertificateChain to getPeerCertificates
  core/src/main/java/io/undertow/attribute/SslClientCertAttribute.java
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/util/Certificates.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
Labels: bug, next release

#1004 UNDERTOW-1806 better HTTP/2 close behaviour
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
  core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
Labels: maintenance branch

#981 UNDERTOW-1806 better HTTP/2 close behaviour
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
  core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
Labels: bug, next release

#985 UNDERTOW-1806 better HTTP/2 close behaviour
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
  core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
Labels: maintenance branch

#983 [UNDERTOW-1821] Path template matched parameters should keep order
  core/src/main/java/io/undertow/util/PathTemplateMatcher.java
  core/src/test/java/io/undertow/util/PathTemplateMatcherTestCase.java
Labels: enhancement, next release

#1007 [UNDERTOW-1787] Issues when undertow is setup behind apache proxy
  core/src/main/java/io/undertow/attribute/SslSessionIdAttribute.java
  core/src/main/java/io/undertow/protocols/ajp/AjpClientRequestClientStreamSinkChannel.java
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
  core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParseState.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLAttributesServlet.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataProxyTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataTestCase.java
  servlet/src/test/resources/dummy.keystore
Labels: bug, maintenance branch

#955 [UNDERTOW-1787] Issues when undertow is setup behind apache proxy
  core/src/main/java/io/undertow/attribute/SslSessionIdAttribute.java
  core/src/main/java/io/undertow/protocols/ajp/AjpClientRequestClientStreamSinkChannel.java
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
  core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParseState.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLAttributesServlet.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataProxyTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataTestCase.java
  servlet/src/test/resources/dummy.keystore
Labels: bug, next release

#1006 [UNDERTOW-1787] Issues when undertow is setup behind apache proxy
  core/src/main/java/io/undertow/attribute/SslSessionIdAttribute.java
  core/src/main/java/io/undertow/protocols/ajp/AjpClientRequestClientStreamSinkChannel.java
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
  core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParseState.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLAttributesServlet.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataProxyTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/security/ssl/SSLMetaDataTestCase.java
  servlet/src/test/resources/dummy.keystore
Labels: bug, maintenance branch

#1011 [UNDERTOW-1745] AccessLogHandler must be invoked also for HTTP2 Upgra…
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: bug, maintenance branch

#1009 [UNDERTOW-1745] AccessLog must contain HTTP2 Upgrade requests too
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: bug, next release

#1012 [UNDERTOW-1745] AccessLogHandler must be invoked also for HTTP2 Upgra…
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: bug, maintenance branch

#999 UNDERTOW-1813 Make PathResourceManager.getResource rethrow a Security…
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: bug, next release

#998 UNDERTOW-1813 Make PathResourceManager.getResource rethrow a Security…
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: bug, maintenance branch

#997 UNDERTOW-1813 Make PathResourceManager.getResource rethrow a Security…
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: bug, maintenance branch
