Repository undertow-io/undertow, pull requests merged in 2020-04, with the labels that each got.

#878 [UNDERTOW-1684] Remove OSGi support
  core/pom.xml
  karaf/pom.xml
  karaf/src/main/resources/features.xml
  pom.xml
  servlet/pom.xml
  servlet/src/main/java/io/undertow/servlet/osgi/Activator.java
  websockets-jsr/pom.xml
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/osgi/Activator.java
Labels: next release

#877 [UNDERTOW-1685] Slight test extension for SameSite cookie support
  core/src/test/java/io/undertow/util/CookiesTestCase.java
  core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
Labels: enhancement, next release

#873 [UNDERTOW-1678] Some tests do not respect value of 'default.server.ad…
  core/src/test/java/io/undertow/server/HttpServerExchangeTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/request/HttpHostValuesTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/request/RedirectTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/request/RequestPathTestCase.java
Labels: bug, next release

#861 [UNDERTOW-1699] Remove unused private fields from Http2ReceiveListener
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: enhancement, next release

#875 UNDERTOW-1701: Fix race condition in GracefulShutdownHandler
  core/src/main/java/io/undertow/server/handlers/GracefulShutdownHandler.java
Labels: bug, next release

#866 UNDERTOW-1700: Prevent resource leaks when exchanges aren't closed cleanly
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: enhancement, next release

#879 [UNDERTOW-1675] Upgrade dependencies for 2.1.0.Final release
  core/pom.xml
  core/src/test/java/io/undertow/server/security/SimpleConfidentialRedirectTestCase.java
  examples/pom.xml
  pom.xml
  servlet/pom.xml
Labels: next release, waiting CI check
