Repository undertow-io/undertow, pull requests merged in 2020-11, with the labels that each got.

#989 UNDERTOW-1807: Fix ForwardedHandlerTestCase on jdk14+
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
Labels: bug, next release

#986 [UNDERTOW-1742] Don't clear attributes in closeAndDrainRequest() method
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, next release

#990 [UNDERTOW-1810] Dynamically determine the major servlet version at ru…
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
Labels: enhancement, next release

#992 UNDERTOW-1807: Fix ForwardedHandlerTestCase on jdk14+
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
Labels: maintenance branch

#993 UNDERTOW-1807: Fix ForwardedHandlerTestCase on jdk14+
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
Labels: maintenance branch

#994 [UNDERTOW-1742] Don't clear attributes in closeAndDrainRequest() method
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: maintenance branch

#995 [UNDERTOW-1742] Don't clear attributes in closeAndDrainRequest() method
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: maintenance branch

#974 UNDERTOW-1792 ServletPrintWriter.println uses LF instead of CRLF
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/test/java/io/undertow/servlet/test/crosscontext/CrossContextClassLoaderTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/forward/MultiPartForwardTestCase.java
Labels: enhancement, next release

#972 UNDERTOW-1792 ServletPrintWriter.println uses LF instead of CRLF
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/test/java/io/undertow/servlet/test/crosscontext/CrossContextClassLoaderTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/forward/MultiPartForwardTestCase.java
Labels: maintenance branch

#973 UNDERTOW-1792 ServletPrintWriter.println uses LF instead of CRLF
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/test/java/io/undertow/servlet/test/crosscontext/CrossContextClassLoaderTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/forward/MultiPartForwardTestCase.java
Labels: maintenance branch
