Repository undertow-io/undertow, pull requests merged in 2020-06, with the labels that each got.

#897 UNDERTOW-1720 fix potential race in senders
  core/src/main/java/io/undertow/io/AsyncSenderImpl.java
  core/src/main/java/io/undertow/io/BlockingSenderImpl.java
  servlet/src/main/java/io/undertow/servlet/core/BlockingWriterSenderImpl.java
Labels: bug, next release

#896 UNDERTOW-1717 Return 416 Range Not Satisfiable when first-byte-pos of…
  core/src/main/java/io/undertow/util/ByteRange.java
  core/src/test/java/io/undertow/server/handlers/RangeRequestTestCase.java
  core/src/test/java/io/undertow/util/ByteRangeTestCase.java
Labels: bug, next release

#902 [UNDERTOW-1722] Resolve memory leak involving request attributes
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, next release

#892 UNDERTOW-1713 Don't start async IO too early
  servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: bug, next release

#898 [UNDERTOW-1719] Handling of path parameters can set incorrect requestURI/requestPath
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Labels: bug, next release

#899 [UNDERTOW-1719] Handling of path parameters can set incorrect requestURI/requestPath
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Labels: bug

#893 Adding test to InMemorySessionTestCase for UNDERTOW-1419
  core/src/test/java/io/undertow/server/handlers/session/InMemorySessionTestCase.java
Labels: enhancement, next release

#904 [UNDERTOW-1726] Disable the JDK9AlpnProvider from being used by defau…
  core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
Labels: bug, next release
