Repository undertow-io/undertow, pull requests merged in 2021-05, with the labels that each got.

#1079 [UNDERTOW-1876] security-manager and reflection permissions in Direct…
  core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java
Labels: bug, next release

#1117 [UNDERTOW-1886] [master] Request dispatcher is returned when the path points to outside the servlet context
  core/src/main/java/io/undertow/util/CanonicalPathUtils.java
  core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardServlet.java
Labels: bug, next release

#1147 Revert "[UNDERTOW-1783] Add support for part specific charsets. Charset is ca…"
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: maintenance branch

#1148 Revert "[UNDERTOW-1783] Add support for part specific charsets. Charset is ca…"
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: maintenance branch

#1149 [UNDERTOW-1877] HTTP2 implementation returns PUSH PROMISES for frames…
  core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushPromisesTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushServlet.java
Labels: maintenance branch

#1150 [UNDERTOW-1877] HTTP2 implementation returns PUSH PROMISES for frames…
  core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushPromisesTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushServlet.java
Labels: maintenance branch

#1151 [UNDERTOW-1886] Add back non-null option to CanonicalPathUtils, while…
  core/src/main/java/io/undertow/util/CanonicalPathUtils.java
  core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug

#1152 [UNDERTOW-1886] Add back nullAllowed option to CanonicalPathUtils, wh…
  core/src/main/java/io/undertow/util/CanonicalPathUtils.java
  core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: maintenance branch

#1153 [UNDERTOW-1886] Add back nullAllowed option to CanonicalPathUtils, wh…
  core/src/main/java/io/undertow/util/CanonicalPathUtils.java
  core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: maintenance branch
