Repository undertow-io/undertow, pull requests merged in 2021-08, with the labels that each got.

#1227 [UNDERTOW-1939] Upload dump files in github actions script
  .github/workflows/ci.yml
Labels: enhancement, next release

#1228 [UNDERTOW-1940][UNDERTOW-1648] Workaround the BindException error by …
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: enhancement, next release

#1229 [UNDERTOW-1941] At Http2ClientTestCase.afterClass(), check if server …
  core/src/test/java/io/undertow/client/http/Http2ClientTestCase.java
Labels: enhancement, next release

#1230 [UNDERTOW-1946] Increate max wait time and wait time in an attempt to…
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Labels: enhancement, next release

#1231 [UNDERTOW-1929] Prevent SocketTimeoutException by tuning up SoTimeout…
  core/src/test/java/io/undertow/testutils/TestHttpClient.java
Labels: enhancement, next release

#1232 [UNDERTOW-1929] At TestHttpClient, apply fix to all proxy tests, and …
  core/src/test/java/io/undertow/testutils/TestHttpClient.java
Labels: enhancement, next release

#1211 [UNDERTOW-1523] Temporarily disable failing tests
  core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
  core/src/test/java/io/undertow/server/handlers/ReceiverTestCase.java
  core/src/test/java/io/undertow/server/handlers/SenderTestCase.java
  core/src/test/java/io/undertow/server/ssl/SimpleSSLTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamSSLTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Labels: enhancement, next release

#1226 [UNDERTOW-1935] - buffer leak on incoming websocket PONG message
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/FrameHandler.java
Labels: bug, next release

#1234 [UNDERTOW-1935] - buffer leak on incoming websocket PONG message
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/FrameHandler.java
Labels: maintenance branch

#1222 [UNDERTOW-1933] Short-circuit logic for boolean (2.2.x)
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
Labels: enhancement, next release

#1224 [UNDERTOW-1933] Short-circuit logic for boolean (2.0.x)
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
Labels: enhancement, maintenance branch

#1225 [UNDERTOW-1932] - unify SSLContext manipulation flow
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java
Labels: bug, next release

#1221 [UNDERTOW-1931] Avoid Nullpointer
  core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
  core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
  core/src/main/java/io/undertow/util/Cookies.java
  core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
Labels: bug, next release

#1235 [UNDERTOW-1931] Avoid Nullpointer
  core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
  core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
  core/src/main/java/io/undertow/util/Cookies.java
  core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
Labels: maintenance branch

#1218 [UNDERTOW-1916] - fix method signature in PathResourceManager
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: enhancement, next release

#1220 [UNDERTOW-1916] - fix method signature in PathResourceManager
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: maintenance branch
