Repository undertow-io/undertow, pull requests merged in 2021-02, with the labels that each got.

#1014 [UNDERTOW-1827] At InMemorySessionManager.Session.requestStarted, bum…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug, next release

#1015 [UNDERTOW-1827] At InMemorySessionManager.Session.requestStarted, bum…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1016 [UNDERTOW-1827] At InMemorySessionManager.Session.requestStarted, bum…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1017 [UNDERTOW-1828] NullPointerException occurred if a servlet calls Http…
  servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug, next release

#1030 [UNDERTOW-1828] NullPointerException occurred if a servlet calls Http…
  servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: maintenance branch

#1029 [UNDERTOW-1828] NullPointerException occurred if a servlet calls Http…
  servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: maintenance branch

#1032 [UNDERTOW-1780][JBEAP-18537] Validating request headers in HTTP2 frames
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: maintenance branch

#1033 [UNDERTOW-1780][JBEAP-18537] Validating request headers in HTTP2 frames
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: maintenance branch

#1036 [UNDERTOW-1839][JBEAP-20636] SSLConduit: synchronize on doWrap/doUnwrap/close to pre…
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  spotbugs-exclude.xml
Labels: maintenance branch

#1035 [UNDERTOW-1839][JBEAP-20636] SSLConduit: synchronize on doWrap/doUnwrap/close to pre…
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  spotbugs-exclude.xml
Labels: maintenance branch

#1034 [UNDERTOW-1839][JBEAP-20636] SSLConduit: synchronize on doWrap/doUnwrap/close to pre…
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  spotbugs-exclude.xml
Labels: bug, next release, waiting CI check

#1025 [UNDERTOW-1833] Unneccessary code removed from the test.
  core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
Labels: enhancement, next release

#1037 [UNDERTOW-1824] AJP handler must send AJP responses for bad requests …
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
Labels: bug, next release

#1013 [UNDERTOW-1785][UNDERTOW-1757][UNDERTOW-1744] Merge Jakarta EE 9 work
  jakartaee9/pom.xml
  jakartaee9/src/main/java/io/undertow/jakartaee9/ArtifactNameTransformer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Deployer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Installer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Transformer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/PomTransformer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/TransformConstants.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/UndertowJakartaEE9Logger.java
  jakartaee9/src/main/resources/META-INF/services/org.wildfly.transformer.TransformerFactory
  jakartaee9/src/main/resources/Version.properties
  pom.xml
Labels: new feature, next release
