Repository undertow-io/undertow, pull requests merged in 2021-07, with the labels that each got.

#1178 [UNDERTOW-1903] Upgrade XNIO to 3.8.4.Final
  pom.xml
Labels: enhancement, next release

#1206 [UNDERTOW-1924] At FixedLengthStreamSourceConduit.read/transferTo met…
  core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java
Labels: bug, next release

#1207 [UNDERTOW-1924] At FixedLengthStreamSourceConduit.read/transferTo met…
  core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java
Labels: maintenance branch

#1209 Improve the CI
  .github/workflows/ci.yml
  core/src/test/java/io/undertow/server/ParseTimeoutTestCase.java
  core/src/test/java/io/undertow/server/WriteTimeoutTestCase.java
  core/src/test/java/io/undertow/server/ssl/ComplexSSLTestCase.java
Labels: enhancement, next release

#1210 Test fixes for maintenance branch
  core/src/test/java/io/undertow/server/ParseTimeoutTestCase.java
  core/src/test/java/io/undertow/server/WriteTimeoutTestCase.java
  core/src/test/java/io/undertow/server/ssl/ComplexSSLTestCase.java
Labels: maintenance branch

#1208 [UNDERTOW-1920] [UNDERTOW-1921][UNDERTOW-1922] Fixes for Jakarta EE9 transformation module
  jakartaee9/pom.xml
  jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Transformer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/PomTransformer.java
  jakartaee9/src/main/java/io/undertow/jakartaee9/UndertowJakartaEE9Logger.java
Labels: enhancement, next release

#1176 [UNDERTOW-1842] At AbstractFramedStreamSinkChannel.flushComplete(), requeue the final frame if we still have a body to be written
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug, next release

#1191 [UNDERTOW-1842] At AbstractFramedStreamSinkChannel.flushComplete(), requeue the final frame if we still have a body to be written
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug, maintenance branch

#1182 [UNDERTOW-1906] Guard against null resource path
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/ClassPathResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug, maintenance branch

#1180 [UNDERTOW-1906] Guard against null resource path
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/ClassPathResourceManager.java
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug, next release

#1185 [UNDERTOW-1905] remove constant multiplication of timeout in Sesssion…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: enhancement, maintenance branch

#1183 [UNDERTOW-1905] remove constant multiplication of timeout in Sesssion…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: enhancement, next release

#1213 [UNDERTOW-1857] Provide a way of performing actions before starts and after server stops in tests
  core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/AbstractModClusterTestBase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/testutils/RunDefaultServer.java
  servlet/src/test/java/io/undertow/servlet/test/security/custom/ServletCustomAuthFormEncodingTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/BinaryEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/JsrWebSocketServer07Test.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/ProgramaticLazyEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/TestMessagesReceivedInOrder.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/AnnotatedAutobahnServer.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/ProgramaticAutobahnServer.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DynamicEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/security/WebsocketBasicAuthTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/stress/WebsocketStressTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/suspendresume/SuspendResumeTestCase.java
Labels: maintenance branch

#1214 [UNDERTOW-1858] Fix ReadTimeoutTestCase
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java
  core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Labels: maintenance branch

#1050 [UNDERTOW-1858] Fix ReadTimeoutTestCase
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java
  core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Labels: bug, enhancement, next release

#1146 UNDERTOW-1894 - Better handling for leading ? on query string
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/server/handlers/SetAttributeTestCase.java
Labels: bug, next release

#1168 UNDERTOW-1984_2.0.x
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/server/handlers/SetAttributeTestCase.java
Labels: bug, maintenance branch

#1215 [UNDERTOW-1856] Suspend reads when starting to a new request at HttpR…
  core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
Labels: bug, next release

#1216 [UNDERTOW-1856] Suspend reads when starting to a new request at HttpR…
  core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
Labels: maintenance branch

#1200 [UNDERTOW-1895] Fix test DefaultServletCachingListenerTestCase.testWelcomePages in JDK11 Ubuntu
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Labels: maintenance branch

#1054 [UNDERTOW-1471] unify secure uri processing for wss and https
  core/src/main/java/io/undertow/websockets/client/WebSocketClient.java
  core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java
Labels: bug, next release

#1094 [UNDERTOW-1471] unify secure uri processing for wss and https
  core/src/main/java/io/undertow/websockets/client/WebSocketClient.java
  core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java
Labels: maintenance branch

#1107 [UNDERTOW-1882] allow HTTP2 to take advantage of UndertowOptions.ALLO…
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2ViaUpgradeTestCase.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2ViaUpgradeWithUnEncodedURLCharactersTestCase.java
Labels: bug, next release

#1109 [UNDERTOW-1882] allow HTTP2 to take advantage of UndertowOptions.ALLO…
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2ViaUpgradeTestCase.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2ViaUpgradeWithUnEncodedURLCharactersTestCase.java
Labels: bug, maintenance branch
