Repository undertow-io/undertow, pull requests merged in 2021-09, with the labels that each got.

#1236 [UNDERTOW-1789] - bumpTImeout on setMaxInactiveInterval
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug, next release

#1238 [UNDERTOW-1789] - bumpTImeout on setMaxInactiveInterval
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1241 [UNDERTOW-1898] DefaultServlet will not serve content from any direct…
  servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Labels: maintenance branch

#1240 [UNDERTOW-1957] Add jakartaee9 artifacts to dependency management ses…
  pom.xml
Labels: bug, next release

#1242 [UNDERTOW-1959] Last attempt to increase the timeout for DefaultServl…
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Labels: enhancement, next release

#1243 [UNDERTOW-1960] Use a latch to prevent Address already in use between…
  core/src/test/java/io/undertow/server/handlers/proxy/AbstractLoadBalancingProxyTestCase.java
Labels: enhancement, next release

#1202 [UNDERTOW-1532] - switch to toRealPath rather than use absolutePath o…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: bug fix, next release

#1203 [UNDERTOW-1917] Logic in try/finally blocks hides exceptions
  core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java
  core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
Labels: bug fix, enhancement, next release

#1172 [UNDERTOW-1899] fix servlet mapping value in case of forward to error…
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: maintenance branch

#1244 [UNDERTOW-1962] Add a StopServerWithExternalWorkerUtils, and make sur…
  core/src/test/java/io/undertow/client/http/AjpClientTestCase.java
  core/src/test/java/io/undertow/client/http/Http2ClientTestCase.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
  core/src/test/java/io/undertow/server/StopTestCase.java
  core/src/test/java/io/undertow/server/handlers/HttpTunnelingViaConnectTestCase.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersProxyTestCase.java
  core/src/test/java/io/undertow/server/handlers/URLDecodingHandlerTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancerConnectionPoolingTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancingProxyWithCustomHostSelectorTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/ProxyPathHandlingTest.java
  core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/AbstractModClusterTestBase.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2ViaUpgradeTestCase.java
  core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
  core/src/test/java/io/undertow/server/protocol/proxy/ProxyProtocolTestCase.java
  core/src/test/java/io/undertow/server/ssl/DelegatedTaskExecutorTestCase.java
  core/src/test/java/io/undertow/server/ssl/TLS13HalfCloseHangTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/testutils/StopServerWithExternalWorkerUtils.java
  core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java
  core/src/test/java/io/undertow/websockets/extensions/WebSocketExtensionBasicTestCase.java
Labels: enhancement, next release

#1160 [UNDERTOW-1198] - fix IPv6 matching regex to include compressed repre…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerUnitTestCase.java
Labels: bug fix, next release

#1162 [UNDERTOW-1198] - fix IPv6 matching regex to include compressed repre…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerUnitTestCase.java
Labels: maintenance branch

#1192 [UNDERTOW-1910] Make sure that AbstractFramedStreamSinkChannel.awaitW…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug fix, next release

#1217 [UNDERTOW-1910] Make sure that AbstractFramedStreamSinkChannel.awaitW…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: maintenance branch

#1233 [UNDERTOW-1929] Increase even more the sockettimeout config to make s…
  core/src/test/java/io/undertow/testutils/TestHttpClient.java
Labels: enhancement, next release

#1205 [UNDERTOW-1950] Fix NullPointerException in PreCompressedResourceSupplier
  core/src/main/java/io/undertow/server/handlers/resource/PreCompressedResourceSupplier.java
  core/src/test/java/io/undertow/server/handlers/file/PreCompressedResourceTestCase.java
  core/src/test/java/io/undertow/server/handlers/file/data1.json
  core/src/test/java/io/undertow/server/handlers/file/data2.json
Labels: bug fix, next release

#1248 [UNDERTOW-1950] Fix NullPointerException in PreCompressedResourceSupplier
  core/src/main/java/io/undertow/server/handlers/resource/PreCompressedResourceSupplier.java
  core/src/test/java/io/undertow/server/handlers/file/PreCompressedResourceTestCase.java
  core/src/test/java/io/undertow/server/handlers/file/data1.json
  core/src/test/java/io/undertow/server/handlers/file/data2.json
Labels: maintenance branch

#1201 [UNDERTOW-1915] Remove unneccesary code
  core/src/main/java/io/undertow/Undertow.java
  core/src/main/java/io/undertow/attribute/RemoteHostAttribute.java
  core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
  core/src/main/java/io/undertow/protocols/ajp/AjpResponseParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
  core/src/main/java/io/undertow/protocols/ssl/SNISSLExplorer.java
  core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
  core/src/main/java/io/undertow/server/handlers/RequestDumpingHandler.java
  core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/ALPNOfferedClientHelloExplorer.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/main/java/io/undertow/util/ETagUtils.java
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/PathMatcher.java
  core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
  servlet/pom.xml
  servlet/src/main/java/io/undertow/servlet/compat/rewrite/Substitution.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/SendHandlerAdapter.java
Labels: enhancement, next release

#1246 [UNDERTOW-1910] Remove UndertowOptions.DEFAULT_WRITE_TIMEOUT, and add…
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug fix, next release

#1116 [UNDERTOW-1568] - add sync block when handling frames in AbstractFram…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: bug fix, maintenance branch

#1114 [UNDERTOW-1568] - add sync block when handling frames in AbstractFram…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: bug fix, next release

#1250 [UNDERTOW-1917] Logic in try/finally blocks hides exceptions
  core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java
  core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
Labels: maintenance branch

#1174 [UNDERTOW-1869] fix concurrency on session creation
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug fix, next release

#1249 [UNDERTOW-1869] fix concurrency on session creation
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1251 [UNDERTOW-1532] - switch to toRealPath rather than use absolutePath o…
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Labels: maintenance branch

#1252 [UNDERTOW-1969] Ignore deprecated certificate retrieval method failure for deprecated parts of Undertow
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
Labels: bug fix, next release

#1255 [UNDERTOW-1969] Throw SSLPeerUnverifiedException from getPeerCertific…
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
Labels: bug fix, next release

#1253 [UNDERTOW-1972] Remove the place holder session and use the session b…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug fix, next release

#1254 [UNDERTOW-1972] Remove the place holder session and use the session b…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch
