Repository undertow-io/undertow, pull requests merged in 2021-03, with the labels that each got.

#1047 Fix minor javadoc mistakes
  core/src/main/java/io/undertow/server/handlers/PathHandler.java
  core/src/main/java/io/undertow/util/PathMatcher.java
Labels: next release

#1043 [UNDERTOW-1852] Add OSGi manifest headers to 3 Undertow modules
  core/pom.xml
  karaf/pom.xml
  karaf/src/main/resources/features.xml
  pom.xml
  servlet/pom.xml
  websockets-jsr/pom.xml
Labels: enhancement, next release

#1039 [UNDERTOW-1845] At the trace logging message, print the listener and …
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: enhancement, next release

#1042 UNDERTOW-1846 Configurable SSLEngine delegated task executor
  core/src/main/java/io/undertow/Undertow.java
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowAcceptingSslChannel.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
  core/src/test/java/io/undertow/server/ssl/DelegatedTaskExecutorTestCase.java
Labels: enhancement, next release

#1040 [UNDERTOW-1847] Add deploy-jakartaee9-artifacts.sh script
  jakartaee9/deploy-jakartaee9-artifacts.sh
Labels: enhancement, next release

#1049 [UNDERTOW-1857] Change the way that DefaultServer operates so that no…
  core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/AbstractModClusterTestBase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/testutils/RunDefaultServer.java
  servlet/src/test/java/io/undertow/servlet/test/security/custom/ServletCustomAuthFormEncodingTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/BinaryEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/JsrWebSocketServer07Test.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/ProgramaticLazyEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/TestMessagesReceivedInOrder.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/AnnotatedAutobahnServer.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/ProgramaticAutobahnServer.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DynamicEndpointTest.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/security/WebsocketBasicAuthTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/stress/WebsocketStressTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/suspendresume/SuspendResumeTestCase.java
Labels: enhancement, next release

#1051 [UNDERTOW-1857] Fix reading of @AfterServerStops methods in DefaultSe…
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: bug, next release

#1038 UNDERTOW-1844: Fix getHttpServletMapping when both prefix and extension match
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatchesData.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/test/java/io/undertow/servlet/test/path/GetMappingServlet.java
  servlet/src/test/java/io/undertow/servlet/test/path/MappingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/path/MultipleMatchingMappingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/path/ServletSpecExampleTestCase.java
Labels: bug

#1066 [UNDERTOW-1832] Use proper stream Id in HttpFramePriority to allow mo…
  core/src/main/java/io/undertow/protocols/http2/Http2FramePriority.java
  core/src/main/java/io/undertow/protocols/http2/Http2PushPromiseStreamSinkChannel.java
Labels: bug, maintenance branch

#1065 [UNDERTOW-1832] Use proper stream Id in HttpFramePriority to allow mo…
  core/src/main/java/io/undertow/protocols/http2/Http2FramePriority.java
  core/src/main/java/io/undertow/protocols/http2/Http2PushPromiseStreamSinkChannel.java
Labels: bug, maintenance branch

#1070 [UNDERTOW-1679] fix normalization of path in PathTemplateMatcher to f…
  core/src/main/java/io/undertow/util/PathTemplateMatcher.java
  core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java
Labels: bug, maintenance branch

#1069 [UNDERTOW-1679] fix normalization of path in PathTemplateMatcher to f…
  core/src/main/java/io/undertow/util/PathTemplateMatcher.java
  core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java
Labels: bug, maintenance branch

#1068 UNDERTOW-1873 Path is not canonicalized when Request.getRequestDispat…
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, maintenance branch

#1067 UNDERTOW-1873 Path is not canonicalized when Request.getRequestDispat…
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, maintenance branch

#1064 UNDERTOW-1873 Path is not canonicalized when Request.getRequestDispat…
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug, next release

#1063 [UNDERTOW-1591] Fix AsyncContext.dispatch() to pass decoded path
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: bug, next release

#1074 [UNDERTOW-1824] AJP handler must send AJP responses for bad requests …
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
Labels: bug, maintenance branch

#1073 [UNDERTOW-1824] AJP handler must send AJP responses for bad requests …
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
Labels: bug, maintenance branch

#1075 [UNDERTOW-1591] Fix AsyncContext.dispatch() to pass decoded path
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: bug, maintenance branch

#1076 [UNDERTOW-1591] Fix AsyncContext.dispatch() to pass decoded path
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: bug, maintenance branch

#1044 [UNDERTOW-1837] ServletRequest#getLocalPort(), getLocalAddr() and get…
  core/src/main/java/io/undertow/server/handlers/ForwardedHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyXForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/constant/GenericServletConstants.java
  servlet/src/test/java/io/undertow/servlet/test/util/ProxyPeerXForwardedHandlerServlet.java
Labels: bug, next release

#1046 [UNDERTOW-1837] ServletRequest#getLocalPort(), getLocalAddr() and get…
  core/src/main/java/io/undertow/server/handlers/ForwardedHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyXForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/constant/GenericServletConstants.java
  servlet/src/test/java/io/undertow/servlet/test/util/ProxyPeerXForwardedHandlerServlet.java
Labels: bug, maintenance branch

#1045 [UNDERTOW-1837] ServletRequest#getLocalPort(), getLocalAddr() and get…
  core/src/main/java/io/undertow/server/handlers/ForwardedHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/ProxyXForwardedTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/constant/GenericServletConstants.java
  servlet/src/test/java/io/undertow/servlet/test/util/ProxyPeerXForwardedHandlerServlet.java
Labels: bug, maintenance branch
