Repository undertow-io/undertow, pull requests merged in 2021-11, with the labels that each got.

#1260 [UNDERTOW-1982] Incorporate deploy-jakartaee9-artifacts.sh script int…
  jakartaee9/deploy-jakartaee9-artifacts.sh
  jakartaee9/pom.xml
  jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Deployer.java
Labels: enhancement, next release

#1258 [UNDERTOW-1981] Unify DefaultServlet & ServletInitialHandler in handling forbidden subpaths
  servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
  servlet/src/main/java/io/undertow/servlet/handlers/Paths.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Labels: bug fix, next release

#1257 [UNDERTOW-1983] Minor refactoring at HttpString
  core/src/main/java/io/undertow/util/HttpString.java
Labels: enhancement, next release

#1261 [UNDERTOW-1984] GOAWAY sent by HTTP2 server when a RST is sent after upgrade
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/client/http/H2CUpgradeResetTestCase.java
Labels: bug fix, next release

#1126 [UNDERTOW-1872] fix ipv6 parsing with trailling empty block
  core/src/main/java/io/undertow/util/NetworkUtils.java
Labels: bug fix, next release

#1128 [UNDERTOW-1872] fix ipv6 parsing with trailling empty block
  core/src/main/java/io/undertow/util/NetworkUtils.java
Labels: maintenance branch

#1262 UNDERTOW-1964 IPAddressAccessControlHandler stops working when ProxyPeerAddressHandler is enabled and X-Forwarded-For request header contains multiple IP addresses
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerWithProxyPeerAddressHandlerTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/testutils/IPv6Ignore.java
  core/src/test/java/io/undertow/testutils/IPv6Only.java
Labels: maintenance branch

#1099 [UNDERTOW-1409] fix percent encoded path redirect
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedToSubPathTestCase.java
Labels: bug fix, next release

#1101 [UNDERTOW-1409] fix percent encoded path redirect
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedToSubPathTestCase.java
Labels: maintenance branch

#1154 [UNDERTOW-1739] allow tested predicate expressions in if/else as per …
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
Labels: bug fix, next release

#1157 [UNDERTOW-1740] fix single predicate termination ";" parsing
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
Labels: bug fix, next release

#1136 [UNDERTOW-318] fix GSSAPI logs
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java
  core/src/main/java/io/undertow/security/impl/GSSAPIAuthenticationMechanism.java
Labels: enhancement, next release

#1138 [UNDERTOW-318] fix GSSAPI logs
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java
  core/src/main/java/io/undertow/security/impl/GSSAPIAuthenticationMechanism.java
Labels: maintenance branch

#1264 [UNDERTOW-1989] Setup actions are not executed when using the async Start method
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleDateThreadLocalAsyncServlet.java
Labels: bug fix, next release

#1086 [UNDERTOW-1786] handle IO properly for async context write
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncListenerOnErrorTest.java
  servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncServlet5.java
Labels: bug fix, next release

#1266 [UNDERTOW-1989] Setup actions are not executed when using the async Start method
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleDateThreadLocalAsyncServlet.java
Labels: maintenance branch

#1088 [UNDERTOW-1786] handle IO properly for async context write
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncListenerOnErrorTest.java
  servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncServlet5.java
Labels: maintenance branch

#1265 [UNDERTOW-1992] Add PooledAdaptor.toString()
  core/src/main/java/io/undertow/util/PooledAdaptor.java
Labels: enhancement, next release

#1102 [UNDERTOW-1883] Allow registering mod_cluster context in stopped or d…
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java
  core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/BasicMCMPUnitTestCase.java
Labels: enhancement, next release

#1263 [UNDERTOW-1883] Allow registering mod_cluster context in stopped or d…
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java
  core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/BasicMCMPUnitTestCase.java
Labels: maintenance branch

#1259 [UNDERTOW-1980] add local vars and sync to handle read source in Abst…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: bug fix, next release

#1267 [UNDERTOW-1993] At AbsractLoadBalancingProxyTestCase.tearDown check i…
  core/src/test/java/io/undertow/server/handlers/proxy/AbstractLoadBalancingProxyTestCase.java
Labels: enhancement, next release

#1270 [UNDERTOW-1984] GOAWAY sent by HTTP2 server when a RST is sent after …
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/client/http/H2CUpgradeResetTestCase.java
Labels: maintenance branch

#1269 [UNDERTOW-1980] Remove synchronized block from close, it is not neces…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: enhancement, next release

#1268 [UNDERTOW-1980] add local vars and sync to handle read source in Abst…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Labels: maintenance branch

#1129 [UNDERTOW-1459] change status code sent on leg for timeouts from 503 …
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Labels: bug fix, next release

#1131 [UNDERTOW-1459] change status code sent on leg for timeouts from 503 …
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Labels: maintenance branch

#1271 Revert "[UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks"
  core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
  core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java
  core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java
  core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
  core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java
  core/src/main/java/io/undertow/server/handlers/cache/LimitedBufferSlicePool.java
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/HeaderMap.java
  core/src/main/java/io/undertow/util/HeaderValues.java
  core/src/main/java/io/undertow/util/HexConverter.java
  core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/SubstringMap.java
  core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
  core/src/main/java9/io/undertow/util/FastConcurrentDirectDeque.java
  servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardRequestWrapper.java
  servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardResponseWrapper.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Labels: next release

#1198 [UNDERTOW-1913]apply ReadTimeoutStreamSourceConduit/WriteTimeoutStrea…
  core/src/main/java/io/undertow/client/http/HttpClientConnection.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
Labels: enhancement, next release

#1272 [UNDERTOW-1913]apply ReadTimeoutStreamSourceConduit/WriteTimeoutStrea…
  core/src/main/java/io/undertow/client/http/HttpClientConnection.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
Labels: maintenance branch
