Repository undertow-io/undertow, pull requests merged in 2021-04, with the labels that each got.

#1026 [UNDERTOW-1834] Fix for IBM JDK and HTTP2/ALPN.
  core/src/main/java/io/undertow/server/protocol/http/ALPNLimitingSSLEngine.java
  core/src/main/java/io/undertow/server/protocol/http/AlpnOpenListener.java
Labels: bug, next release

#1090 [UNDERTOW-1501] - fix timing bug in websocket container that can caus…
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/SessionContainer.java
Labels: bug, next release

#1091 [UNDERTOW-1501] - fix timing bug in websocket container that can caus…
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/SessionContainer.java
Labels: bug, maintenance branch

#1092 [UNDERTOW-1501] - fix timing bug in websocket container that can caus…
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/SessionContainer.java
Labels: bug, maintenance branch

#1096 [UNDERTOW-1468] - File upload form -replace existing instead of break…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
Labels: bug, next release

#1097 [UNDERTOW-1468] - File upload form -replace existing instead of break…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
Labels: bug, maintenance branch

#1098 [UNDERTOW-1468] - File upload form -replace existing instead of break…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
Labels: bug

#1085 [UNDERTOW-1877] HTTP2 implementation returns PUSH PROMISES for frames…
  core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushPromisesTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/push/PushServlet.java
Labels: bug, next release

#1105 [UNDERTOW-1783] Add support for part specific charsets. Charset is ca…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: enhancement, maintenance branch

#1106 [UNDERTOW-1783] Add support for part specific charsets. Charset is ca…
  core/src/main/java/io/undertow/server/handlers/form/FormData.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
  servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Labels: enhancement, maintenance branch
