Repository undertow-io/undertow, pull requests merged in 2022-09, with the labels that each got.

#1355 [UNDERTOW-2138] Removing unnecessary JDK8 reflection hacks - API is available on supported JDKs
  core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
  core/src/main/java/io/undertow/protocols/alpn/ModularJdkAlpnProvider.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackClientByteArrayOutputStream.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackClientHelloExplorer.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackServerByteArrayOutputStream.java
  core/src/main/java/io/undertow/protocols/ssl/ALPNHackServerHelloExplorer.java
  core/src/main/resources/META-INF/services/io.undertow.protocols.alpn.ALPNProvider
  spotbugs-exclude.xml
Labels: enhancement, next release

#1373 [UNDERTOW-2159] add null check to SessionManager
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug fix, next release

#1338 [UNDERTOW-2109] The large file is in unexpected location on JDK17
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
Labels: bug fix, next release

#1371 [UNDERTOW-2160] FileHandlerTestCase.testFileTransferLargeFile improvement
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
Labels: bug fix, next release

#1369 UNDERTOW-2145 OutputStreams only awaitWritable after a write returns zero
  core/src/main/java/io/undertow/io/UndertowOutputStream.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: enhancement, next release, waiting CI check

#1363 UNDERTOW-2142 ChunkedStreamSinkConduit.write writes all requested buffers
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/test/java/io/undertow/server/handlers/ChunkedResponseTransferCodingTestCase.java
Labels: bug fix, next release

#1199 UNDERTOW-1902 Undertow allows session creation and session ID change after response is committed.
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug fix, next release, new feature/API change

#1370 [UNDERTOW-2147] fix race condition between session changeSessionId and invalidate"
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1375 [UNDERTOW-2147] fix race condition between session changeSessionId an…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug fix, next release

#1368 [UNDERTOW-2140] improve cipher suite len match
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
Labels: bug fix, next release

#1376 [UNDERTOW-2159][UNDERTOW-2145][UNDERTOW-2140][UNDERTOW-2142][UNDERTOW-2109] Port fixes
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/main/java/io/undertow/io/UndertowOutputStream.java
  core/src/main/java/io/undertow/server/SSLSessionInfo.java
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
  core/src/test/java/io/undertow/server/handlers/ChunkedResponseTransferCodingTestCase.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: maintenance branch
