Repository undertow-io/undertow, pull requests merged in 2022-05, with the labels that each got.

#1314 [UNDERTOW-2061] prefix not formed properly in ACL
  core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java
  core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerUnitTestCase.java
Labels: bug fix, next release

#1313 [UNDERTOW-2081] Proceed if RejectedExecutionException is thrown
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowSession.java
Labels: bug fix, next release

#1323 [UNDERTOW-1593-2.3.x] [master] Port request tracking from 2.2.x
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/RequestStatistics.java
  core/src/main/java/io/undertow/server/handlers/ActiveRequestTrackerHandler.java
  core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
  core/src/test/java/io/undertow/server/handlers/ActiveRequestTrackerTest.java
Labels: next release, new feature/API change

#1318 [UNDERTOW-2092] Update GitHub CI configuration to JDK11+
  .github/workflows/ci.yml
Labels: enhancement, next release

#1317 [UNDERTOW-2091] spotbugs-maven-plugin needs to be updated to work with JDK17
  pom.xml
Labels: enhancement, next release
