Repository undertow-io/undertow, pull requests merged in 2022-12, with the labels that each got.

#1403 [UNDERTOW-2198] Add Option to force the SNIHostName
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
  core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
Labels: waiting PR update

#1402 [UNDERTOW-2198] Add Option to force the SNIHostName
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
  core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
Labels: new feature/API change

#1399 [UNDERTOW-2188] fix deny-uncovered methods to work properly in corner…
  servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
Labels: bug fix, next release

#1410 [UNDERTOW-2184] - properly propagate sessionChanged callback
  servlet/src/main/java/io/undertow/servlet/core/SessionListenerBridge.java
Labels: maintenance branch

#1423 [UNDERTOW-2209] Ignore defaultPath security when it is not configured at all
  servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
Labels: maintenance branch

#1427 [UNDERTOW-2023] Update README file, extracting contributing and security
  CODEOWNERS
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: enhancement, next release

#1429 [UNDERTOW-2213] Revert deny-uncovered-methods fix for corner case
  servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
Labels: bug fix, next release
