Repository undertow-io/undertow, pull requests merged in 2022-06, with the labels that each got.

#1320 [UNDERTOW-2093][UNDERTOW-2096] Fix CI, with spotbugs fully passing
  .github/workflows/ci.yml
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  pom.xml
  spotbugs-exclude.xml
Labels: next release, waiting CI check

#1312 [UNDERTOW-2036] At AbstractFramedStreamSinkChannel.awaitWritable, gua…
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug fix, next release

#1326 [UNDERTOW-2052] Move Undertow to Servlet API 6.0.0
  pom.xml
Labels: next release, dependency upgrade

#1327 [UNDERTOW-2098] Update version of `wildfly-openssl` library that is u…
  pom.xml
Labels: next release, dependency upgrade

#1334 [UNDERTOW-2102] ServletPrintWriterDelegate throws exception using OpenJDK 19 EA
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriterDelegate.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ExceptionWriterServlet.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterTestCase.java
Labels: bug fix, maintenance branch

#1335 [UNDERTOW-2102] ServletPrintWriterDelegate throws exception using OpenJDK 19 EA
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriterDelegate.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ExceptionWriterServlet.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterTestCase.java
Labels: bug fix, next release

#1331 [UNDERTOW-2060] fix double AJP response
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
Labels: bug fix, next release

#1330 [UNDERTOW-2034][UNDERTOW-2035][UNDERTOW-2079][UNDERTOW-2080] Fixes for AbstractFramedStreamSinkChannel and Http2StreamSinkChannel await methods
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: bug fix, next release

#1329 [UNDERTOW-2036][UNDERTOW-2034][UNDERTOW-2035][UNDERTOW-2060][UNDERTOW-2066][UNDERTOW-2067][UNDERTOW-2068][UNDERTOW-1945][UNDERTOW-2079][UNDERTOW-2080][UNDERTOW-2074]Port fixes to 2.2.x branch
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
  pom.xml
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Labels: maintenance branch

#1332 [UNDERTOW-1945] ServletOutputStreamTestCase fails with Premature end of chunk coded message body
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Labels: bug fix, next release

#1337 [UNDERTOW-2094] fix relative redirect with trailing slash context
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServletTestCase.java
Labels: bug fix, next release

#1319 [UNDERTOW-2094] fix relative redirect with trailing slash context
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServletTestCase.java
Labels: maintenance branch
