Repository undertow-io/undertow, pull requests merged in 2022-04, with the labels that each got.

#1304 [UNDERTOW-2028] Buffer leak error involving AjpServerResponseConduit
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerResponseConduit.java
Labels: bug fix, next release

#1300 UNDERTOW-2038: InputStream.read implementations avoid unnecessary ByteBuffer.wrap
  core/src/main/java/io/undertow/io/UndertowInputStream.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/UpgradeServletInputStream.java
Labels: enhancement, next release

#1302 [UNDERTOW-2041] Allow leading zeroes for ipv6 addresses
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
Labels: bug fix, next release

#1305 [UNDERTOW-2022] Add resumeReads to FixedLengthStreamSourceConduit
  core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java
Labels: bug fix, next release

#1309 [UNDERTOW-2070] At ServletOutputStreamImpl, allow redirects with cont…
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectWithContentLengthServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectWithContentLengthTestCase.java
Labels: bug fix, next release

#1308 [UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks
  core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
  core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java
  core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java
  core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
  core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java
  core/src/main/java/io/undertow/server/handlers/cache/LimitedBufferSlicePool.java
  core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/HeaderMap.java
  core/src/main/java/io/undertow/util/HeaderValues.java
  core/src/main/java/io/undertow/util/HexConverter.java
  core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/SubstringMap.java
  core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
  core/src/main/java9/io/undertow/util/FastConcurrentDirectDeque.java
  servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardRequestWrapper.java
  servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardResponseWrapper.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Labels: enhancement, next release

#1311 [UNDERTOW-2074] Upgrade XNIO to 3.8.7.Final (fixes UNDERTOW-2073)
  pom.xml
Labels: next release, dependency upgrade
