Repository undertow-io/undertow, pull requests merged in 2022-08, with the labels that each got.

#1354 [UNDERTOW-2135] Partial revert of hack from commit id: 55445de
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
Labels: bug fix, next release

#1357 [UNDERTOW-2124] ProgramaticLazyEndpointTest and BinaryEndpointTest failures with JDK-17
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug fix, next release

#1358 [UNDERTOW-2124] ProgramaticLazyEndpointTest and BinaryEndpointTest failures with JDK-17
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug fix, maintenance branch

#1347 [UNDERTOW-2125] [UNDERTOW-2083] Fixes for ReadTimeoutStreamSourceConduit
  core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java
Labels: bug fix, next release

#1359 [UNDERTOW-2031][UNDERTOW-2113][UNDERTOW-2130][UNDERTOW-2133][UNDERTOW-2135] backport bug fixes to 2.2.x branch
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
  core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
  core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseClientServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ForceDrainServlet.java
Labels: maintenance branch

#1292 [UNDERTOW-1934] invoke onClose in case of network failure
  core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
  core/src/main/java/io/undertow/websockets/core/WebSocketMessages.java
  core/src/test/java/io/undertow/websockets/core/protocol/AbstractWebSocketServerTest.java
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: bug fix, next release

#1339 [UNDERTOW-2112] Client Cert Renegotiation is not supported by JDK14 and newer.
  core/src/test/java/io/undertow/server/security/ClientCertRenegotiationTestCase.java
Labels: enhancement, next release

#1325 [UNDERTOW-2097] DMI_RANDOM_USED_ONLY_ONCE error reported by spotbugs
  core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
  core/src/main/java/io/undertow/websockets/client/WebSocket13ClientHandshake.java
  spotbugs-exclude.xml
Labels: enhancement, next release
