Repository undertow-io/undertow, pull requests merged in 2022-10, with the labels that each got.

#1382 [UNDERTOW-2048] At UndertowInputStream, do not block undefinitely whe…
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/io/UndertowInputStream.java
Labels: bug fix, waiting CI check

#1377 [UNDERTOW-2111] rewrite should match "path" matching with and without…
  core/src/main/java/io/undertow/server/handlers/builder/RewriteHandlerBuilder.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: bug fix, next release

#1379 [UNDERTOW-2163] Predicate Language cannot set attribute to empty string
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/builder/PredicatedHandlersParserTestCase.java
Labels: bug fix, next release, waiting CI check

#1378 UNDERTOW-2162: Only canonicalize the servlet path when getting request dispatcher
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
Labels: bug fix, next release

#1362 [UNDERTOW-2141] Fix NPE and add a test for it
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletBrokenSessionFactoryTestCase.java
Labels: bug fix, next release, waiting CI check

#926 [UNDERTOW-1771] APIs deprecated in JDK 9+ are in use
  core/src/main/java/io/undertow/attribute/SslClientCertAttribute.java
  core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
  core/src/main/java/io/undertow/server/ConnectionSSLSessionInfo.java
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
  core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2SslSessionInfo.java
  core/src/main/java/io/undertow/util/Certificates.java
  core/src/main/java/io/undertow/util/HttpString.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
Labels: enhancement, next release

#1383 [UNDERTOW-2167] 2.2.x branch will provide Java EE API version only
  jakarta/examples/pom.xml
  jakarta/pom.xml
  jakarta/servlet/pom.xml
  jakarta/websockets-jsr/pom.xml
  pom.xml
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
Labels: enhancement, maintenance branch

#1384 [UNDERTOW-1818] AbstractServletInputStreamTestCase.runTestParallel fails with bytes out of order
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AsyncInputStreamServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AsyncOutputStreamServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
Labels: bug fix, next release

#1381 Final Undertow Master Cleanup
  benchmarks/pom.xml
  core/pom.xml
  coverage-report/pom.xml
  dist/assembly.xml
  dist/pom.xml
  examples/pom.xml
  karaf/pom.xml
  karaf/src/main/resources/features.xml
  parser-generator/pom.xml
  pom.xml
  servlet/pom.xml
  websockets-jsr/pom.xml
Labels: enhancement, next release

#1360 [UNDERTOW-2069] Fix the deadlock and add a test for it
  servlet/src/main/java/io/undertow/servlet/core/ManagedFilter.java
  servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilter.java
  servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilterTestCase.java
Labels: bug fix, next release

#1388 [UNDERTOW-2176] ActiveRequestTrackerTest.testRequestTracking fails intermittently
  core/src/test/java/io/undertow/server/handlers/ActiveRequestTrackerTest.java
Labels: enhancement, next release, waiting CI check

#1389 [UNDERTOW-2171..UNDERTOW-2175][UNDERTOW-2177..UNDERTOW-2183] Dependencies upgrade
  core/src/test/java/io/undertow/server/handlers/JDBCLogDatabaseTestCase.java
  pom.xml
Labels: enhancement, next release

#1367 UNDERTOW-2143 Deflaters operate directly on ByteBuffers
  core/src/main/java/io/undertow/conduits/DeflatingStreamSinkConduit.java
  core/src/main/java/io/undertow/conduits/GzipStreamSinkConduit.java
Labels: bug fix, next release

#1390 [UNDERTOW-2185] Upgrade Apache DS to 2.0.0.AM26
  core/pom.xml
  core/src/test/java/io/undertow/server/handlers/BlockingReadTimeoutHandlerTestCase.java
  core/src/test/java/io/undertow/server/handlers/URLDecodingHandlerTestCase.java
  core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
  core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java
  core/src/test/java/io/undertow/server/security/SpnegoAuthenticationTestCase.java
  core/src/test/java/io/undertow/testutils/HttpClientUtils.java
  core/src/test/java/io/undertow/websockets/extensions/AutobahnExtensionCustomReceiverServer.java
  core/src/test/java/io/undertow/websockets/extensions/AutobahnExtensionsServer.java
  pom.xml
Labels: enhancement, next release

#1392 [UNDERTOW-2123] always URL decode pathInfo and servletPath as required by Servlet specification
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug fix, maintenance branch, waiting peer review

#1394 [UNDERTOW-2123] always URL decode pathInfo and servletPath as required by Servlet specification
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: bug fix, next release

#1398 [UNDERTOW-2081] Proceed if RejectedExecutionException is thrown
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowSession.java
Labels: bug fix, maintenance branch
