Repository undertow-io/undertow, pull requests merged in 2022-07, with the labels that each got.

#1324 [UNDERTOW-2095] undertow-examples dependency duplicated in root pom.xml file
  pom.xml
Labels: enhancement, next release

#1344 [UNDERTOW-2122] Javax imports in servlet tests
  core/pom.xml
  servlet/pom.xml
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServlet.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServletTestCase.java
  websockets-jsr/pom.xml
Labels: bug fix, next release

#1346 [UNDERTOW-2116] ServletOutputStreamImpl incorrectly sets Content-Length to 0
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/SimpleServletTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectWithContentLengthTestCase.java
Labels: bug fix, next release

#1345 [UNDERTOW-2116] ServletOutputStreamImpl incorrectly sets Content-Length to 0
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/test/java/io/undertow/servlet/test/SimpleServletTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectWithContentLengthTestCase.java
Labels: maintenance branch

#1348 [UNDERTOW-2130] Classes witch annotation RunWith are triggered as TestCase
  servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseClientServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ForceDrainServlet.java
Labels: enhancement, next release

#1351 [UNDERTOW-2134] At WebSocketClient13TestCase, fail if request to conn…
  core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java
Labels: enhancement, next release

#1350 [UNDERTOW-2133] CVE-2022-2053 Handle RequestTooBigException
  core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
Labels: bug fix, next release

#1349 [UNDERTOW-2131] ContentEncodingRepository avoids iterator allocations
  core/src/main/java/io/undertow/server/handlers/encoding/ContentEncodingRepository.java
  core/src/main/java/io/undertow/util/QValueParser.java
Labels: enhancement, next release

#1321 [UNDERTOW-2031] protocol error with HTTP/2 and Expect: 100-continue
  core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
Labels: bug fix, next release

#1340 [UNDERTOW-2113] Read Timeout Test Case Fail on Windows with JDK17 due to different exception message
  core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Labels: enhancement, next release
