Repository undertow-io/undertow, pull requests merged in 2022-11, with the labels that each got.

#1397 Upstream backports to 2.2.x branch
  core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/main/java/io/undertow/server/handlers/builder/RewriteHandlerBuilder.java
  core/src/main/java/io/undertow/websockets/client/WebSocket13ClientHandshake.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
  core/src/test/java/io/undertow/server/handlers/builder/PredicatedHandlersParserTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  servlet/src/main/java/io/undertow/servlet/core/ManagedFilter.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilter.java
  servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilterTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletBrokenSessionFactoryTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AsyncInputStreamServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/AsyncOutputStreamServlet.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
  spotbugs-exclude.xml
Labels: waiting CI check, maintenance branch

#1393 [UNDERTOW-2054] Buffer leak errors involving SslConduit on CI
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug fix, next release

#1396 [UNDERTOW-2190] DefaultServlet serves CSS and JS blobs even if directory listing is disabled
  core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
  servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletNoDirectoryListingTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java
Labels: bug fix, next release

#1404 [UNDERTOW-2189] IOException thrown when trying to close already closed stream
  core/src/main/java/io/undertow/channels/DetachableStreamSourceChannel.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: bug fix, next release

#1401 [UNDERTOW-2204] Add a CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
Labels: enhancement, next release

#1400 [UNDERTOW-2196] Reduce allocations caused by HttpString
  core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Labels: bug fix, next release

#1406 [UNDERTOW-2022] At MultipartParser.MultipartUploadHandler.close, clea…
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
Labels: bug fix, next release

#1407 [UNDERTOW-2186] allow WEB-INF or META-INF subdirectory access
  servlet/src/main/java/io/undertow/servlet/handlers/Paths.java
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/foo/meta-inf/notsecret
  servlet/src/test/java/io/undertow/servlet/test/defaultservlet/foo/web-inf/notsecret
Labels: bug fix, next release

#1411 [UNDERTOW-1591][UNDERTOW-2123][UNDERTOW-2206] IAE trying to decode a requestPath
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchServlet.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/spec/PathTestCase.java
Labels: bug fix, next release

#1412 [UNDERTOW-1591][UNDERTOW-2123][UNDERTOW-2206] IAE trying to decode a requestPath (2.2.x)
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchServlet.java
  servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/spec/PathTestCase.java
Labels: bug fix, maintenance branch
