Repository undertow-io/undertow, pull requests merged in 2023-04, with the labels that each got.

#1459 [UNDERTOW-1938] Resolve MaxRequestSizeTestCase flakiness on Windows
  core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: enhancement, next release

#1446 [UNDERTOW-2245]javax.servlet.forward.mapping request attribute is not…
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/NextServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/util/DispatcherUtil.java
  servlet/src/test/java/io/undertow/servlet/test/util/DeploymentUtils.java
Labels: bug fix, next release

#1445 [UNDERTOW-2245]javax.servlet.forward.mapping request attribute is not…
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/NextServlet.java
  servlet/src/test/java/io/undertow/servlet/test/dispatcher/util/DispatcherUtil.java
  servlet/src/test/java/io/undertow/servlet/test/util/DeploymentUtils.java
Labels: waiting PR update, maintenance branch

#1463 [UNDERTOW-2260] Removing unused Jetty ALPN provider - it was targeting JDK8 and below
  core/pom.xml
  core/src/main/java/io/undertow/protocols/alpn/JettyAlpnProvider.java
  core/src/main/resources/META-INF/services/io.undertow.protocols.alpn.ALPNProvider
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  pom.xml
Labels: enhancement, next release

#1467 [UNDERTOW-2258] Fix the new method HeaderMap.putAll
  core/src/main/java/io/undertow/util/HeaderMap.java
Labels: bug fix, next release

#1385 [UNDERTOW-2251] At Http2DataStreamSinkChannel, dot not send END_STREA…
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
Labels: bug fix, next release

#1466 [UNDERTOW-2246] tweak DirectByteBufferDeallocator to detect hardcoded…
  core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java
Labels: bug fix, next release

#1469 [UNDERTOW-1938][UNDERTOW-2259][UNDERTOW-2258][UNDERTOW-2246][UNDERTOW-2251] Backport bug fixes
  core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java
  core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSourceChannel.java
  core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java
  core/src/main/java/io/undertow/util/HeaderMap.java
  core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancerConnectionPoolingTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: maintenance branch

#1471 [UNDERTOW-2263] UNDERTOW-2093 detailed followup
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/io/BlockingReceiverImpl.java
  core/src/main/java/io/undertow/io/BlockingSenderImpl.java
  core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
  core/src/main/java/io/undertow/server/handlers/resource/URLResource.java
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
  spotbugs-exclude.xml
Labels: enhancement, next release
