Repository undertow-io/undertow, pull requests merged in 2023-03, with the labels that each got.

#1451 [UNDERTOW-2250] Update the ci.yml file replacing joschi/setup-jdk wit…
  .github/workflows/ci.yml
Labels: enhancement, next release

#1447 [UNDERTOW-2212] CVE-2022-4492 Server identity in https connection is …
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/client/http/HttpClientProvider.java
  core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
  core/src/test/java/io/undertow/client/http/Http2ClientTestCase.java
  core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
Labels: bug fix, next release

#1441 [UNDERTOW-1875] - add system property to allow ID less matrix parameters
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
Labels: enhancement, next release

#1453 [UNDERTOW-2239] CVE-2023-1108 At SslConduit.wrapAndFlip, do not attem…
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug fix, next release

#1452 [UNDERTOW-2252] Potential fix for the SslConduit.dataToUnwrap buffer leak
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Labels: bug fix, next release

#1456 [UNDERTOW-2253] Fix the CI script so it can run again
  .github/workflows/ci.yml
Labels: maintenance branch

#1395 [UNDERTOW-2192] session.getServletContext returns wrong context with shared-session-config
  servlet/src/main/java/io/undertow/servlet/core/SessionListenerBridge.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: maintenance branch

#1457 [UNDERTOW-2207][UNDERTOW-2212][UNDERTOW-2239][UNDERTOW-2252] 2.2.x backport bug fixes
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/client/http/HttpClientProvider.java
  core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
  core/src/main/java/io/undertow/io/UndertowOutputStream.java
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
  core/src/test/java/io/undertow/client/http/Http2ClientTestCase.java
  core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
  core/src/test/java/io/undertow/server/handlers/blocking/BlockingServerStreamClosureTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamClosureTestCase.java
Labels: maintenance branch
