Repository undertow-io/undertow, pull requests merged in 2023-10, with the labels that each got.

#1513 UNDERTOW-2305 Fix NPE in Http2ClearClientProvider
  core/src/main/java/io/undertow/client/http2/Http2ClearClientProvider.java
Labels: bug fix, next release

#1521 [UNDERTOW-2271] CVE-2023-3223 Large uploaded file does not persist to disk if the f…
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
Labels: bug fix, next release

#1333 [UNDERTOW-2072] DefaultByteBufferPool.getBuffer() may return null
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Labels: bug fix, next release

#1522 [UNDERTOW-2313] NPE occurs in session invalidation if a session creat…
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: bug fix, next release

#1519 [UNDERTOW-2313] NPE occurs in session invalidation if a session creation attempt hits UNDERTOW-1971
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: maintenance branch

#1520 [UNDERTOW-2316] Unify InMemorySessionManager with DistributableSessionManager - allow null exchanges
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Labels: enhancement, next release

#1523 [UNDERTOW-2305][UNDERTOW-2271][UNDERTOW-2072] CVE-2023-3223 Backport bug fixes
  core/src/main/java/io/undertow/client/http2/Http2ClearClientProvider.java
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
  core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
Labels: maintenance branch

#1515 [UNDERTOw-2310][UNDERTOW-2311] Introducing Missing Default Constants
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: enhancement, next release

#1525 [UNDERTOW-2323] Fix for CVE-2023-44487 and related issues
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/client/http2/DoSHttp2ClientConnection.java
  core/src/test/java/io/undertow/protocols/http2/RapidResetDDoSUnitTestCase.java
Labels: bug fix, next release

#1527 [UNDERTOW-2329][UNDERTOW-2324] Add release 8 to maven-compiler-plugin config in pom.…
  pom.xml
Labels: enhancement, maintenance branch

#1526 [UNDERTOW-2323][UNDERTOW-2311][UNDERTOW-2310][UNDERTOW-2327] CVE-2023-44487 backport fixes to branch 2.2.x
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/client/http2/DoSHttp2ClientConnection.java
  core/src/test/java/io/undertow/protocols/http2/RapidResetDDoSUnitTestCase.java
Labels: maintenance branch

#1528 [UNDERTOW-2330] At HttpReadListener, handle race when connection is s…
  core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
Labels: bug fix, next release
