Repository undertow-io/undertow, pull requests merged in 2023-06, with the labels that each got.

#1483 [UNDERTOW-2056][UNDERTOW-2075][UNDERTOW-2076][UNDERTOW-2077][UNDERTOW-2137] CVE-2022-1259 and related fixes
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
  core/src/main/java/io/undertow/util/ReferenceCountedPooled.java
  core/src/test/java/io/undertow/client/http/Http2WindowUpdateTimeoutTestCase.java
Labels: maintenance branch

#1482 [UNDERTOW-2277] Prevent writing more than content length at ServletOu…
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: bug fix, waiting CI check

#1188 [UNDEDRTOW-1896] - fix parsing of trailing :: in IPv6
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
Labels: bug fix, next release

#1465 [UNDERTOW-2216] fix resource serving via predicates + test
  core/src/main/java/io/undertow/attribute/RequestURLAttribute.java
  core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/test/java/io/undertow/server/handlers/ResourcePredicateHandlerTestCase.java
  servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Labels: bug fix, next release

#1443 [UNDERTOW-2243] At ServletOutputStreamImpl.updateWritten, flush the c…
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: enhancement, next release

#1472 [UNDERTOW-2255] Solve the Hpack decoding exception
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancingProxyWithHeaderTableSizeSettingsTestCase.java
Labels: bug fix, next release

#1484 [UNDERTOW-2250][UNDERTOW-2277][UNDERTOW-1896][UNDERTOW-2216][UNDERTOW-2243][UNDERTOW-2255] Backport fixes to 2.2.x branch
  .github/workflows/ci.yml
  core/src/main/java/io/undertow/attribute/RequestURLAttribute.java
  core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
  core/src/test/java/io/undertow/server/handlers/ResourcePredicateHandlerTestCase.java
  core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
  servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: maintenance branch

#1481 UNDERTOW-2276: Fix NPE in HeaderMap.contains
  core/src/main/java/io/undertow/util/HeaderMap.java
  core/src/test/java/io/undertow/util/HeaderMapTestCase.java
Labels: bug fix, next release

#1473 [UNDERTOW-2267] Align Servlet.init() method behaviour with previous JBoss Web implementation
  servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
Labels: enhancement, next release

#1479 [UNDERTOW-2270] io.undertow.servlet.spec.HttpServletRequestImpl NPE thrown
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Labels: maintenance branch

#1490 [UNDERTOW-2241][UNDERTOW-2247][UNDERTOW-2248] Handle write timeout properly so no chunk errors occur
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Labels: bug fix, next release

#1491 [UNDERTOW-2241][UNDERTOW-2247][UNDERTOW-2248] Handle write timeout properly so no chunk errors occur
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Labels: maintenance branch

#1492 [UNDERTOW-2276] [UNDERTOW-2267] Backport fixes to 2.2.x branch
  core/src/main/java/io/undertow/util/HeaderMap.java
  core/src/test/java/io/undertow/util/HeaderMapTestCase.java
  servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
Labels: maintenance branch

#1475 UNDERTOW-2228 Undertow write-timeout can cause a truncate response for request coming through keep-alive connection
  core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/server/MultipleRequestsWriteTimeoutTestCase.java
Labels: bug fix, next release

#1480 UNDERTOW-2275 Suspend reads before terminating a request to cleanup r…
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Labels: bug fix, next release

#1493 [UNDERTOW-2282] Upgrade spotbugs to 4.7.3.4
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  core/src/main/java/io/undertow/util/FlexBase64.java
  pom.xml
Labels: next release, dependency upgrade

#1494 UNDERTOW-2228 Reset write timeout on suspendWrites()
  core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/test/java/io/undertow/server/MultipleRequestsWriteTimeoutTestCase.java
Labels: maintenance branch

#1499 [UNDERTOW-2281] At Http2FrameHeaderParser, throw a protocol error for headers not followed by data
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
Labels: maintenance branch

#1498 [UNDERTOW-2281] At Http2FrameHeaderParser, throw a protocol error for headers not followed by data
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
Labels: bug fix, next release, waiting CI check
