Repository undertow-io/undertow, pull requests merged in 2023-01, with the labels that each got.

#1432 UNDERTOW-2221 Path param parsing not resumed correctly
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/test/java/io/undertow/server/protocol/http/ParserResumeTestCase.java
Labels: maintenance branch

#1417 [UNDERTOW-1748] add comment line to predicates
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/predicate/PredicateParsingTestCase.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: enhancement, next release

#1420 [UNDERTOW-2208] Enhance SNI hostname creation exception text
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Labels: enhancement, next release

#1421 [UNDERTOW-2208][2.2.x] Enhance SNI hostname creation exception text
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Labels: maintenance branch

#1187 [UNDERTOW-1890] - fix NetworkUtils exceptions
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/util/NetworkUtils.java
  core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
Labels: enhancement, under verification

#1164 [UNDERTOW-1885] remove escape char from delimitered strings
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: enhancement, next release

#1166 [UNDERTOW-1885] remove escape char from delimitered strings
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: enhancement, maintenance branch

#1194 [UNDERTOW-1442] Add exchange attribute to display start of processing
  core/src/main/java/io/undertow/attribute/ExchangeStartTimeAttribute.java
  core/src/main/resources/META-INF/services/io.undertow.attribute.ExchangeAttributeBuilder
Labels: enhancement, next release, new feature/API change

#1133 [UNDERTOW-1875] - add system property to allow ID less matrix parameters
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
Labels: enhancement, next release

#1424 [UNDERTOW-2210] Improved write ASCII path on ServletPrintWriter
  benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncoders.java
  benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncodingBenchmark.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: enhancement, next release

#1433 [UNDERTOW-2211] Fix deny uncovered methods handling
  servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletSecurityConstraintHandler.java
  servlet/src/test/java/io/undertow/servlet/test/security/constraint/AuthenticationMessageServlet.java
  servlet/src/test/java/io/undertow/servlet/test/security/constraint/DenyUncoveredHttpMethodsTestCase.java
Labels: bug fix, next release

#1435 [UNDERTOW-2234] HttpClientSNITestCase fails with last jdk 11.0.18 and 17.0.6
  core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
Labels: bug fix, next release
