Repository undertow-io/undertow, pull requests merged in 2023-02, with the labels that each got.

#1430 [UNDERTOW-2218] add default mime for webp
  core/src/main/java/io/undertow/util/MimeMappings.java
Labels: enhancement, next release

#1438 [UNDERTOW-2200] - Path and query parameters are not decoded properly …
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/handlers/URLDecodingHandler.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpOpenListener.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  core/src/main/java/io/undertow/util/URLUtils.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: bug fix, enhancement, next release

#1439 [UNDERTOW-2242][UNDERTOW-1875][UNDERTOW-1442][UNDERTOW-1748] Revert new features from maintenance release
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/attribute/ExchangeStartTimeAttribute.java
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/resources/META-INF/services/io.undertow.attribute.ExchangeAttributeBuilder
  core/src/test/java/io/undertow/predicate/PredicateParsingTestCase.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Labels: next release

#1440 [UNDERTOW-1885][UNDERTOW-2203][UNDERTOW-2210][UNDERTOW-2211] Backport fixes to 2.2.x branch
  CODEOWNERS
  CONTRIBUTING.md
  README.md
  SECURITY.md
  benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncoders.java
  benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncodingBenchmark.java
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletSecurityConstraintHandler.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/test/java/io/undertow/servlet/test/security/constraint/AuthenticationMessageServlet.java
  servlet/src/test/java/io/undertow/servlet/test/security/constraint/DenyUncoveredHttpMethodsTestCase.java
Labels: waiting CI check, maintenance branch

#1409 UNDERTOW-2207: UndertowOutputStream allows flush after writes
  core/src/main/java/io/undertow/io/UndertowOutputStream.java
  core/src/test/java/io/undertow/server/handlers/blocking/BlockingServerStreamClosureTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamClosureTestCase.java
Labels: bug fix, next release
