Repository undertow-io/undertow, pull requests merged in 2024-10, with the labels that each got.

#1667 [UNDERTOW-2449] Fix PushResourceRSTTestCase
  .github/workflows/ci.yml
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Labels: enhancement, next release

#1661 [UNDERTOW-2436] fix HttpServerExchange state flag race conditions
  core/src/main/java/io/undertow/server/HttpServerExchange.java
Labels: bug fix, next release

#1644 [UNDERTOW-2422] Return the protocol field of the HttpServerExchange into the status line
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java
Labels: bug fix, next release

#1669 [UNDERTOW-2279] Re-enable LotsOfHeadersResponseTestCase in Windows
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Labels: enhancement, next release

#1642 [UNDERTOW-1748] add comment line to predicates
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/predicate/PredicateParsingTestCase.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: next release, new feature/API change

#1662 [UNDERTOW-2444] Fix RST scenario violation in H2
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
Labels: bug fix, next release, waiting peer review

#1672 [UNDERTOW-2457] Share bytes across multiples attempts to parse v1 by …
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
Labels: bug fix, next release

#1674 [UNDERTOW-2483] - marked deprecated field forRemoval
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: enhancement, next release, new feature/API change

#1678 [UNDERTOW-2481] Add DEFAULT_HTTP2_SETTINGS_INITIAL_WINDOW_SIZE
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
Labels: enhancement, next release, new feature/API change

#1676 [UNDERTOW-2495] adds DEFAULT_QUEUED_FRAMES_LOW_WATERMARK
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: enhancement, next release, new feature/API change

#1682 [UNDERTOW-2449] Revert changes that have been merged by mistake in CI…
  .github/workflows/ci.yml
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Labels: enhancement, next release

#1683 [UNDERTOW-2448] At ServletPrintWriter.write(CharBuffer) do not mark e…
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: bug fix, next release

#1534 [UNDERTOW-2333] Undertow read/write timeout should not apply to WebSockets or SSE
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
  core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: enhancement, new feature/API change

#1687 [UNDERTOW-2412 / 2445 / 2449 / 2446 / 2436 / 2422 / 2444 / 2448] Backport fixes to 2.3.x
  .github/workflows/ci.yml
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/attribute/StoredResponse.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
  core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: backport

#1684 [UNDERTOW-2333_2.3.x] Undertow read/write timeout should not apply to WebSockets or SSE
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
  core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: backport, new sys property

#1689 [UNDERTOW-2412 / 2445 / 2449 / 2446 / 2436 / 2422 / 2444 / 2448] Backport fixes to 2.2.x
  .github/workflows/ci.yml
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/attribute/StoredResponse.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
  core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Labels: backport

#1685 [UNDERTOW-2333_2.2.x] Undertow read/write timeout should not apply to WebSockets or SSE
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
  core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
  core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Labels: backport, new sys property

#1694 [UNDERTOW-2518] At WebSocketTimeoutTestCase, use a longer watch timeout
  core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
Labels: enhancement, next release

#1691 [UNDERTOW-2457] Backport: Share bytes across multiples attempts to parse v1 by …
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
Labels: backport

#1686 Revert "[UNDERTOW-2279] Re-enable LotsOfHeadersResponseTestCase in Wi…
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Labels: enhancement

#1660 [UNDERTOW-2404] Add default sorting by type and name in directory lis…
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerIndexTestCase.java
Labels: enhancement, new feature/API change

#1690 [UNDERTOW-2505] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.suspendresume
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/suspendresume/SuspendResumeTestCase.java
Labels: enhancement, next release, hacktoberfest-accepted

#1693 [UNDERTOW-2509] Add 413 response code to overflowing multipart in default async handler
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
Labels: bug fix, next release

#1692 [UNDERTOW-2504] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.security
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/security/WebsocketBasicAuthTestCase.java
Labels: enhancement, next release, hacktoberfest-accepted
