Repository undertow-io/undertow, pull requests merged in 2024-04, with the labels that each got.

#1580 [UNDERTOW-2374] Move the check for allowUnescapedCharactersInUrl to o…
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Labels: enhancement, next release

#1565 [UNDERTOW-2354] Prevent NPE in Bootstrap$WebSocketListener.contextDestroyed
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/Bootstrap.java
Labels: bug fix, next release

#1581 [UNDERTOW-2264] CVE-2023-1973 Force session timeout to 2 minutes when…
  core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Labels: bug fix, next release, waiting CI check

#1535 [UNDERTOW-2375] Minor fixes in contributing guide: broken links, types, style fixes.
  CONTRIBUTING.md
Labels: enhancement, next release

#1573 [UNDERTOW-2291] Shush jdoc and compile warning obfuscating console
  pom.xml
Labels: enhancement, next release

#1582 [UNDERTOW-2347] [UNDERTOW-1926] [UNDERTOW-2351] Backport fixes to 2.2.x branch
  core/src/main/java/io/undertow/client/http/HttpClientProvider.java
  core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
  core/src/test/java/io/undertow/server/handlers/SenderTestCase.java
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadAnnotatedEndpointTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadOnMessageEndpoint.java
Labels: maintenance branch

#1572 [UNDERTOW-2354] Prevent NPE in Bootstrap.contextDestroyed
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/Bootstrap.java
Labels: maintenance branch

#1583 [UNDERTOW-2264] [UNDERTOW-2374] [UNDERTOW-2375] CVE-2023-1973 Backport fixes/enhancements to 2.2.x branch
  CONTRIBUTING.md
  core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Labels: maintenance branch

#1584 [UNDERTOW-2376] Enforce to build using JDK8 for 2.2.x branch
  pom.xml
Labels: waiting CI check, maintenance branch
