Repository undertow-io/undertow, pull requests merged in 2024-07, with the labels that each got.

#1628 [UNDERTOW-2398] Tweak workflow to allow manual re-runs
  .github/workflows/ci.yml
Labels: backport

#1620 [UNDERTOW-2398] Tweak workflow to allow manual re-runs
  .github/workflows/ci.yml
Labels: backport

#1629 [UNDERTOW-2397] Properly index huffman table on encoding
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
Labels: backport

#1621 [UNDERTOW-2397] Properly index huffman table on encoding
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
Labels: backport

#1631 [UNDERTOW-2386] Update ci.yml git doc link
  .github/workflows/ci.yml
Labels: backport

#1623 [UNDERTOW-2386] Update ci.yml git doc link
  .github/workflows/ci.yml
Labels: backport

#1632 [UNDERTOW-2357] remove JDK check in Http2 example
  examples/src/main/java/io/undertow/examples/http2/Http2Server.java
Labels: backport

#1633 [UNDERTOW-2193] Add uniform unity description to UndertowOptions
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: enhancement, backport

#1624 [UNDERTOW-2193] Add uniform unity description to UndertowOptions
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: enhancement, backport

#1634 [UNDERTOW-2046] X-Forwarded-For is IP header, not hostname
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Labels: backport

#1630 [UNDERTOW-2343] properly handle zealous RST frames in case client ca…
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Labels: backport

#1622 [UNDERTOW-2343] properly handle zealous RST frames in case client ca…
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Labels: backport

#1625 [UNDERTOW-2046] X-Forwarded-For is IP header, not hostname
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Labels: backport

#1627 [UNDERTOW-2033] Derive SecurePredicate from connection encryption, ra…
  core/src/main/java/io/undertow/predicate/SecurePredicate.java
Labels: backport

#1626 [UNDERTOW-2033] Derive SecurePredicate from connection encryption, ra…
  core/src/main/java/io/undertow/predicate/SecurePredicate.java
Labels: backport

#1639 [UNDERTOW-2382] CVE-2024-3653 Switch to LRUCache to store entries in cache in LearningPushHandler
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
  core/src/main/java/io/undertow/server/handlers/PathHandler.java
  core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
  core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: bug fix, next release

#1640 [UNDERTOW-2413][UNDERTOW-2382] CVE-2024-5971 CVE-2024-3653 Backport bug fixes
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
  core/src/main/java/io/undertow/server/handlers/PathHandler.java
  core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
  core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: waiting CI check, backport

#1641 [UNDERTOW-2413][UNDERTOW-2382] CVE-2024-5971 CVE-2024-3653 Backport bug fixes
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
  core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
  core/src/main/java/io/undertow/server/handlers/PathHandler.java
  core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
  core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Labels: backport

#1082 [UNDERTOW-1901] - fix max entity handling for multipart
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Labels: enhancement, next release, new feature/API change

#1577 [UNDERTOW-2039] Convert AbstractFramedChannel.AWAIT_WRITABLE_TIMEOUT to nanoseconds
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Labels: enhancement, next release

#1558 [UNDERTOW-2256] Resource predicate presentation differs depending on how it is set up
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
Labels: enhancement, next release

#1554 [UNDERTOW-2321] add "commonv" pattern to accesslog
  core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java
Labels: next release, new feature/API change

#1544 [UNDERTOW-2230] Add priority to HandlerBuilder to override internal h…
  core/src/main/java/io/undertow/predicate/PredicatesHandler.java
  core/src/main/java/io/undertow/server/JvmRouteHandler.java
  core/src/main/java/io/undertow/server/handlers/AccessControlListHandler.java
  core/src/main/java/io/undertow/server/handlers/ActiveRequestTrackerHandler.java
  core/src/main/java/io/undertow/server/handlers/AllowedMethodsHandler.java
  core/src/main/java/io/undertow/server/handlers/BlockingHandler.java
  core/src/main/java/io/undertow/server/handlers/ByteRangeHandler.java
  core/src/main/java/io/undertow/server/handlers/CanonicalPathHandler.java
  core/src/main/java/io/undertow/server/handlers/DisableCacheHandler.java
  core/src/main/java/io/undertow/server/handlers/DisallowedMethodsHandler.java
  core/src/main/java/io/undertow/server/handlers/ForwardedHandler.java
  core/src/main/java/io/undertow/server/handlers/HttpContinueAcceptingHandler.java
  core/src/main/java/io/undertow/server/handlers/HttpTraceHandler.java
  core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java
  core/src/main/java/io/undertow/server/handlers/JDBCLogHandler.java
  core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
  core/src/main/java/io/undertow/server/handlers/LocalNameResolvingHandler.java
  core/src/main/java/io/undertow/server/handlers/PathSeparatorHandler.java
  core/src/main/java/io/undertow/server/handlers/PeerNameResolvingHandler.java
  core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
  core/src/main/java/io/undertow/server/handlers/RedirectHandler.java
  core/src/main/java/io/undertow/server/handlers/RequestBufferingHandler.java
  core/src/main/java/io/undertow/server/handlers/RequestDumpingHandler.java
  core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java
  core/src/main/java/io/undertow/server/handlers/ResponseRateLimitingHandler.java
  core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/SameSiteCookieHandler.java
  core/src/main/java/io/undertow/server/handlers/SecureCookieHandler.java
  core/src/main/java/io/undertow/server/handlers/SetAttributeHandler.java
  core/src/main/java/io/undertow/server/handlers/SetErrorHandler.java
  core/src/main/java/io/undertow/server/handlers/SetHeaderHandler.java
  core/src/main/java/io/undertow/server/handlers/StoredResponseHandler.java
  core/src/main/java/io/undertow/server/handlers/StuckThreadDetectionHandler.java
  core/src/main/java/io/undertow/server/handlers/URLDecodingHandler.java
  core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java
  core/src/main/java/io/undertow/server/handlers/builder/HandlerBuilder.java
  core/src/main/java/io/undertow/server/handlers/builder/ResponseCodeHandlerBuilder.java
  core/src/main/java/io/undertow/server/handlers/builder/RewriteHandlerBuilder.java
  core/src/main/java/io/undertow/server/handlers/encoding/EncodingHandler.java
  core/src/main/java/io/undertow/server/handlers/encoding/RequestEncodingHandler.java
  core/src/main/java/io/undertow/server/handlers/error/FileErrorPageHandler.java
  core/src/main/java/io/undertow/server/handlers/form/EagerFormParsingHandler.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandlerBuilder.java
  core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
  servlet/src/main/java/io/undertow/servlet/handlers/MarkSecureHandler.java
Labels: enhancement, next release

#1543 [UNDERTOW-2229] Add priority to PredicateBuilder to override internal…
  core/src/main/java/io/undertow/predicate/AuthenticationRequiredPredicate.java
  core/src/main/java/io/undertow/predicate/ContainsPredicate.java
  core/src/main/java/io/undertow/predicate/EqualsPredicate.java
  core/src/main/java/io/undertow/predicate/ExistsPredicate.java
  core/src/main/java/io/undertow/predicate/IdempotentPredicate.java
  core/src/main/java/io/undertow/predicate/MaxContentSizePredicate.java
  core/src/main/java/io/undertow/predicate/MethodPredicate.java
  core/src/main/java/io/undertow/predicate/MinContentSizePredicate.java
  core/src/main/java/io/undertow/predicate/PathMatchPredicate.java
  core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java
  core/src/main/java/io/undertow/predicate/PathSuffixPredicate.java
  core/src/main/java/io/undertow/predicate/PathTemplatePredicate.java
  core/src/main/java/io/undertow/predicate/PredicateBuilder.java
  core/src/main/java/io/undertow/predicate/RegularExpressionPredicate.java
  core/src/main/java/io/undertow/predicate/RequestLargerThanPredicate.java
  core/src/main/java/io/undertow/predicate/RequestSmallerThanPredicate.java
  core/src/main/java/io/undertow/predicate/SecurePredicate.java
  servlet/src/main/java/io/undertow/servlet/predicate/DirectoryPredicate.java
  servlet/src/main/java/io/undertow/servlet/predicate/DispatcherTypePredicate.java
  servlet/src/main/java/io/undertow/servlet/predicate/FilePredicate.java
Labels: enhancement, next release

#1540 [UNDERTOW-2325] change SecureCookieCommitListener to also look throug…
  core/src/main/java/io/undertow/server/SecureCookieCommitListener.java
  core/src/test/java/io/undertow/server/handlers/SecureCookieHandlerTestCase.java
Labels: enhancement, next release

#1506 [UNDERTOW-2295] Stop registration of managed default servlet in case default servlet exists
  servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
Labels: bug fix, next release

#1502 [UNDERTOW-2287] Add ACL style ip-match predicate
  core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
  core/src/main/java/io/undertow/predicate/ip/IPMatchPredicate.java
  core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java
  core/src/main/resources/META-INF/services/io.undertow.predicate.PredicateBuilder
  core/src/test/java/io/undertow/server/handlers/IPMatchPredicateTestCase.java
Labels: enhancement, next release, new feature/API change

#1413 [UNDERTOW-1737] add failure-reason to AccessControlListHandler
  core/src/main/java/io/undertow/Handlers.java
  core/src/main/java/io/undertow/server/handlers/AccessControlListHandler.java
  core/src/test/java/io/undertow/server/handlers/UserAgentAccessControlHandlerUnitTestCase.java
Labels: enhancement, next release, new feature/API change

#1141 [UNDERTOW-1485] fix some wrong letter
  core/src/main/java/io/undertow/UndertowMessages.java
  servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Labels: enhancement, new feature/API change

#1186 [UNDERTOW-1904] remove exception flow control
  core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
  core/src/main/java/io/undertow/server/session/Session.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpSessionImpl.java
Labels: enhancement, next release, new feature/API change

#1564 [UNDERTOW-2249] Change that HttpClientConnection.sendRequest on a clo...
  core/src/main/java/io/undertow/client/UndertowClientMessages.java
  core/src/main/java/io/undertow/client/ajp/AjpClientConnection.java
  core/src/main/java/io/undertow/client/http/HttpClientConnection.java
  core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
Labels: enhancement, next release, new feature/API change

#1539 [UNDERTOW-2335] Add an example of the PredicatesHandler and specifically the predicate handler parser
  examples/src/main/java/io/undertow/examples/predicates/PredicateParser.java
Labels: enhancement, next release

#1586 [UNDERTOW-2381] Fix huffman decoding error when EOS literal contains …
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
  core/src/test/java/io/undertow/protocols/http2/HpackHuffmanDecodingStringLiteralRepresentation.java
Labels: bug fix, next release

#1110 [UNDERTOW-1870] - make AsyncContext.timeout configurable per deployment
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Labels: next release, new feature/API change
