Repository undertow-io/undertow, pull requests merged in 2024-08, with the labels that each got.

#1651 [UNDERTOW-2256][UNDERTOW-2381] Backport fixes to 2.2.x
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/test/java/io/undertow/protocols/http2/HpackHuffmanDecodingStringLiteralRepresentation.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
Labels: waiting CI check, backport

#1650 [UNDERTOW-2417][UNDERTOW-2256][UNDERTOW-2381] Backport fixes to 2.3.x
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
  core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
  core/src/test/java/io/undertow/protocols/http2/HpackHuffmanDecodingStringLiteralRepresentation.java
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
  pom.xml
Labels: backport

#1649 [UNDERTOW-2256] Add missing header
  core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
Labels: enhancement, next release

#1646 [UNDERTOW-2425] At ServletOutputStreamImpl synchronized workflow (lis…
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  spotbugs-exclude.xml
Labels: bug fix, next release

#1648 UNDERTOW-2424: Prevent connection access-after-free allowed through ChunkedStreamSinkConduit
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java
Labels: bug fix, next release

#1516 [UNDERTOW-2312] multibytes language in URL request to http/https are …
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
  core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
Labels: bug fix, next release

#1652 [UNDERTOW-2312][UNDERTOW-2425][UNDERTOW-2424] Backport fixes
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
  core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java
  core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  spotbugs-exclude.xml
Labels: backport

#1653 [UNDERTOW-2312][UNDERTOW-2425][UNDERTOW-2424] Backport fixes
  core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
  core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java
  core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
  servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
  servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
  spotbugs-exclude.xml
Labels: backport

#1657 [UNDERTOW-2429] CVE-2024-7885 Fix ProxyProtocolReadListener leak betw…
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
Labels: bug fix, next release
