Repository undertow-io/undertow, pull requests merged in 2024-03, with the labels that each got.

#1559 [UNDERTOW-2280][UNDERTOW-2336][UNDERTOW-2339] CVE-2023-5379 CVE-2024-1459 CVE-2024-1635 Backport bug fixes
  core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/ParseState.java
  core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Labels: maintenance branch

#1562 [UNDERTOW-2321] invoke thread setup actions only when deployment is i…
  servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadAnnotatedEndpointTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadOnMessageEndpoint.java
Labels: enhancement, next release

#1563 [UNDERTOW-2353] A few adjustments to make Undertow build and test on JDK21
  .github/workflows/ci.yml
  core/src/main/java/io/undertow/util/HeaderValues.java
  pom.xml
Labels: enhancement, next release

#1561 [UNDERTOW-2347] Always specify at least http/1.1 in application_layer_protocol_negotiation ALPN extension when doing TLS
  core/src/main/java/io/undertow/client/http/HttpClientProvider.java
  core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
Labels: bug fix, next release
