Repository undertow-io/undertow, pull requests merged in 2024-11, with the labels that each got.

#1700 [UNDERTOW-2503] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.reconnect
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
Labels: enhancement, waiting peer review, hacktoberfest-accepted

#1697 [UNDERTOW-2502] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.extension
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
Labels: enhancement, next release, hacktoberfest-accepted

#1696 [UNDERTOW-2499] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.annotated
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/ThreadSafetyEndpoint.java
Labels: enhancement, next release, hacktoberfest-accepted

#1695 [UNDERTOW-2501] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.dynamicupgrade
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DoUpgradeServlet.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/EchoProgramaticEndpoint.java
Labels: enhancement, next release, hacktoberfest-accepted

#1699 [UNDERTOW-2520] Fix close code constants
  core/src/main/java/io/undertow/websockets/core/CloseMessage.java
Labels: bug fix, next release

#1698 [UNDERTOW-2519] At ProxyHandler append the non-decoded query string to the request
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
Labels: bug fix, next release

#1549 [UNDERTOW-2344] Take into account that close could run concurrently with a read operation
  servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
Labels: bug fix, next release

#1578 [UNDERTOW-2361] handle inflater wrapping properly in deflate encoding
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/conduits/GzipStreamSourceConduit.java
  core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
  core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase.java
Labels: next release

#1574 [UNDERTOW-2371] initialize the DefaultServer once to speed up test HttpContinueSslServletTestCase
  servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java
  servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueSslServletTestCase.java
Labels: enhancement, waiting PR update, under verification, waiting CI check

#1571 [UNDERTOW-2301] add ability to configure http2 per listener
  core/src/main/java/io/undertow/Undertow.java
  core/src/test/java/io/undertow/server/protocol/http2/HTTP2OnListenerTestCase.java
Labels: enhancement, next release, new feature/API change

#1533 [UNDERTOW-2319] Move io.undertow.multipart.minsize property to UndertowOptions
  core/src/main/java/io/undertow/UndertowOptions.java
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
Labels: enhancement, next release, new feature/API change
