Repository undertow-io/undertow, pull requests merged in 2024-09, with the labels that each got.

#1658 [UNDERTOW-2429] CVE-2024-7885 Fix ProxyProtocolReadListener leak betw…
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
Labels: backport

#1545 [UNDERTOW-2412] Read stored json with default UTF-8 encoding
  core/src/main/java/io/undertow/attribute/StoredResponse.java
Labels: enhancement, under verification

#1575 [UNDERTOW-2273] Change ExchangeAttributeParser so it correctly handle…
  core/src/main/java/io/undertow/attribute/ExchangeAttributeParser.java
  core/src/test/java/io/undertow/attribute/ExchangeAttributeParserTest.java
Labels: enhancement, new feature/API change

#1659 [UNDERTOW-2429] CVE-2024-7885 Fix ProxyProtocolReadListener leak betw…
  core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
Labels: backport

#1656 [UNDERTOW-2432] Bump jdoc plugin to 3.3.0+
  pom.xml
Labels: dependency upgrade

#1665 [UNDERTOW-2445] Fix the CI by upgrading all instances of upload-artif…
  .github/workflows/ci.yml
Labels: enhancement
