Repository undertow-io/undertow, pull requests merged in 2024-06, with the labels that each got.

#1532 UNDERTOW-2332 CachingResource mishandling with TTL =0 and FS exhaustion
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingSender.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
  core/src/main/java/io/undertow/server/handlers/resource/CachedResource.java
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
Labels: bug fix, next release

#1601 [UNDERTOW-2400] Fix ResponseWriterTestCase failures
  servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterOnPostServlet.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterOnPostServlet.java
Labels: enhancement, next release

#1599 [UNDERTOW-2385] Use synchronized WeakHashMap in DefaultByteBufferPool
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Labels: bug fix, next release

#1585 [UNDERTOW-2378] Adjust properly session timeout also for alternative AUTH mechanisms
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Labels: bug fix, next release

#1588 [UNDERTOW-2383] do not canonicalize query string in sendRedirect location
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
Labels: bug fix, next release

#1603 [UNDERTOW-2405] CVE-2024-27316 Fix vulnerability by limiting the numb…
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpOpenListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2OpenListener.java
Labels: bug fix, next release

#1592 [UNDERTOW-2391] CVE-2023-5685 bump xnio to bring in fix for the CVE
  pom.xml
Labels: next release, dependency upgrade

#1606 [UNDERTOW-2407][UNDERTOW-2408] Prevent the NPE at DefaultByteBufferPool.close() and minor code enhancements
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Labels: bug fix, next release

#1604 [UNDERTOW-2405] CVE-2024-27316 Add system property io.undertow.http2-max-header-size (default value set to 20000)
  core/pom.xml
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpOpenListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2OpenListener.java
  core/src/test/java/io/undertow/server/handlers/DefaultMaxHeaderTestCase.java
  core/src/test/java/io/undertow/server/handlers/LongURLTestCase.java
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
  core/src/test/java/io/undertow/server/handlers/LotsOfQueryParametersTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: bug fix, next release

#1609 [UNDERTOW-2334] CVE-2024-6162 AJP Parser: Do not share the decodeBuff…
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
Labels: bug fix, next release

#1608 [UNDERTOW-2409] Adjust properly session timeout also in case when GET requests with custom auth mechanisms are used
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Labels: bug fix, next release

#1610 [UNDERTOW-2291][UNDERTOW-2332][UNDERTOW-2400][UNDERTOW-2385] Backport bug fixes to 2.2.x branch
  core/src/main/java/io/undertow/UndertowLogger.java
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
  core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingSender.java
  core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
  core/src/main/java/io/undertow/server/handlers/resource/CachedResource.java
  core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
  pom.xml
  servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterOnPostServlet.java
  servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterOnPostServlet.java
Labels: maintenance branch

#1605 [UNDERTOW-2383] do not canonicalize query string in sendRedirect location
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
Labels: maintenance branch

#1607 [UNDERTOW-2409] Adjust properly session timeout also in case when GET requests with custom auth mechanisms are used
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Labels: maintenance branch

#1611 [UNDERTOW-2415] Disable CI tests for JDK8 in MacOS
  .github/workflows/ci.yml
Labels: enhancement, maintenance branch

#1612 [UNDERTOW-2405][UNDERTOW-2391][UNDERTOW-2407][UNDERTOW-2408][UNDERTOW-2334] CVE-2024-27316 CVE-2023-5685 CVE-2024-6162 Backport bug fixes to 2.2.x
  core/pom.xml
  core/src/main/java/io/undertow/UndertowMessages.java
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
  core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java
  core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/test/java/io/undertow/server/handlers/DefaultMaxHeaderTestCase.java
  core/src/test/java/io/undertow/server/handlers/LongURLTestCase.java
  core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
  core/src/test/java/io/undertow/server/handlers/LotsOfQueryParametersTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
  pom.xml
Labels: maintenance branch

#1597 [UNDERTOW-2398] Tweak workflow to allow manual re-runs
  .github/workflows/ci.yml
Labels: enhancement, next release

#1617 [UNDERTOW-2417] Fix typo in pom config for show warnings
  pom.xml
Labels: enhancement, next release

#1596 [UNDERTOW-2397] Properly index huffman table on encoding
  core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
Labels: next release

#1595 [UNDERTOW-2343] properly handler zealous RST frames in case client ca…
  core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
  core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Labels: bug fix, next release

#1590 [UNDERTOW-2386] Update ci.yml git doc link
  .github/workflows/ci.yml
Labels: enhancement, next release

#1570 [UNDERTOW-2357] remove JDK check in Http2 exapmle
  examples/src/main/java/io/undertow/examples/http2/Http2Server.java
Labels: enhancement, next release

#1568 [UNDERTOW-2193] Add uniform unity description to UndertwoOptions
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: enhancement, next release

#1569 [UNDERTOW-2046] X-Forwarded-For is IP header, not hostname
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Labels: bug fix, next release

#1619 [UNDERTOW-2288_2] Allow new lines inside handlers/predicates to make …
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerUnitTestCase.java
Labels: next release, new feature/API change

#1618 [UNDERTOW-2110] Allow line breaks before predicate operator and befor…
  core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
  core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Labels: next release, new feature/API change
