Repository undertow-io/undertow, pull requests merged in 2025-07, with the labels that each got.

#1734 [UNDERTOW-2569] At the parent pom, set the javadoc source version to …
  pom.xml
Labels: enhancement, next release

#1736 [UNDERTOW-2532] At WebSocketSessionRemoteEndpoint, prevent the NPE by setting a local sender field before checking for null
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/JsrWebSocketMessages.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
Labels: bug fix, next release

#1740 [UNDERTOW-2573] At MultiPartParserDefinition.create, only set the exch…
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
Labels: bug fix, next release

#1742 [UNDERTOW-2481] At UndertowOptions, fix the order of the comments for…
  core/src/main/java/io/undertow/UndertowOptions.java
Labels: next release, new feature/API change

#1730 [UNDERTOW-2564] Verify the signature of the @BeforeServerStarts and @…
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: enhancement, next release

#1743 [UNDERTOW-2518] Tidy up the WebSocketTimeoutTestCase a bit more
  core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
Labels: enhancement, next release

#1749 [UNDERTOW-2506 / 2503 / 2502 / 2499 / 2501 / 2520] Backport fixes to 2.2.x
  core/src/main/java/io/undertow/websockets/core/CloseMessage.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/ThreadSafetyEndpoint.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DoUpgradeServlet.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/EchoProgramaticEndpoint.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
  websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/stress/WebsocketStressTestCase.java
Labels: backport

#1753 [UNDERTOW-2511 / 2538 / 2532 / 2547 ] CVE-2024-4109 Backport fixes to 2.2.x
  core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
  core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
  servlet/src/main/java/io/undertow/servlet/attribute/ServletRelativePathAttribute.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
Labels: backport

#1759 [UNDERTOW-2555 / 2562 / 2563 / 2565 / 2566 / 2567 ] Backport fixes to 2.2.x
  core/src/main/java/io/undertow/server/Connectors.java
  core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
  core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
  core/src/test/java/io/undertow/server/AbstractRedirectURIParseTest.java
  core/src/test/java/io/undertow/server/RedirectURIParseTestCase.java
  core/src/test/java/io/undertow/server/RedirectURIParseWithAllowUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/server/RedirectURIParseWithDecodeSlashTestCase.java
  core/src/test/java/io/undertow/server/RedirectURIParseWithDecodeURLTestCase.java
  core/src/test/java/io/undertow/server/handlers/AbstractQueryParametersTest.java
  core/src/test/java/io/undertow/server/handlers/QueryParametersDefaultConfigTestCase.java
  core/src/test/java/io/undertow/server/handlers/QueryParametersTestCase.java
  core/src/test/java/io/undertow/server/handlers/QueryParametersWithAllowUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: backport

#1766 [UNDERTOW-2586] Upgrade JBoss Threads to 3.7.0.Final
  pom.xml
Labels: next release, dependency upgrade

#1763 [UNDERTOW-2568][UNDERTOW-2569] Backport fixes and enhancements to 2.2.x
  benchmarks/pom.xml
  core/src/main/java/io/undertow/client/UndertowClient.java
  core/src/main/java/io/undertow/client/http/HttpClientProvider.java
  core/src/main/java/io/undertow/security/handlers/SecurityActions.java
  core/src/main/java/io/undertow/security/impl/SecurityActions.java
  core/src/main/java/io/undertow/security/impl/SecurityContextImpl.java
  core/src/main/java/io/undertow/server/HttpServerExchange.java
  core/src/main/java/io/undertow/server/handlers/LocalNameResolvingHandler.java
  core/src/main/java/io/undertow/server/handlers/PeerNameResolvingHandler.java
  core/src/main/java/io/undertow/server/handlers/resource/SecurityActions.java
  core/src/main/java/io/undertow/server/protocol/ajp/SecurityActions.java
  core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
  core/src/main/java/io/undertow/util/FlexBase64.java
  core/src/main/java/io/undertow/util/UrlDecodeException.java
  core/src/test/java/io/undertow/server/DirectByteBufferDeallocatorTestCase.java
  examples/pom.xml
  pom.xml
  servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
  servlet/src/main/java/io/undertow/servlet/api/SecurityActions.java
  servlet/src/main/java/io/undertow/servlet/core/SecurityActions.java
  servlet/src/main/java/io/undertow/servlet/core/SessionListenerBridge.java
  servlet/src/main/java/io/undertow/servlet/handlers/SecurityActions.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
  servlet/src/main/java/io/undertow/servlet/handlers/ServletRequestContext.java
  servlet/src/main/java/io/undertow/servlet/handlers/SessionRestoringHandler.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/CachedAuthenticatedSessionHandler.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
  servlet/src/main/java/io/undertow/servlet/handlers/security/ServletSingleSignOnAuthenticationMechanism.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/HttpSessionImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/SecurityActions.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
  servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriterDelegate.java
  servlet/src/main/java/io/undertow/servlet/util/SavedRequest.java
  servlet/src/main/java/io/undertow/servlet/websockets/SecurityActions.java
  servlet/src/test/java/io/undertow/servlet/test/request/HttpHostValuesTestCase.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/JsrWebSocketFilter.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/SecurityActions.java
  websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Labels: backport

#1757 [UNDERTOW-2576] ProxyHandler can throw NullPointerException if the source address SocketAddress has no ip address
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
Labels: bug fix, next release

#1768 [UNDERTOW-2573 / 2564 / 2556 / 2574 / 2576 ] Backport fixes and enhancements to 2.2.x
  core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
  core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
  core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
  core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
  core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
  core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
  core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
  core/src/test/java/io/undertow/testutils/DefaultServer.java
Labels: waiting CI check, backport
