Repository undertow-io/undertow, pull requests merged in 2025-09, with the labels that each got.

#1755 [UNDERTOW-2522] Make maven compiler plugin fail on error so it does n…
  pom.xml
Labels: enhancement

#1783 [UNDERTOW-2601] Update staging repository from wildfly-staging to jbo…
  pom.xml
Labels: enhancement, next release

#1796 [UNDERTOW-2604]: fix request decompression when multiple buffers must be allocated
  core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
  core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase.java
Labels: bug fix, next release
